### ISSUE TITLE
Crash after enabling dark mode and gradient progress indicator, thereafter Crash at app start

### ISSUE THREAD

**Issue by sp-icy** [dmfs/opentasks#1016]
## Problem

The app (OpenTasks 1.4.1 from F-Droid) crashed after changing some settings. Now it crashes immediately again every time when I try to start the app. No chance to change back the settings.

As a user I would like to use the app again. ;-)

## Detailed steps that led to the problem

It's just a brain dump. I can't exactly reproduce it. I can't access/use the app.

- Entering settings
- Enabling dark mode
- Entering settings
- Enabling second option from the bottom. I just remember "gradient" or something similar.
- Right then the app vanished.

Maybe next time I shouldn't be that curious. ;-)

## Quick search within existing issues

Perhaps the following tickets are involved. They are quite recent.

- Consider restoring previous progress indicator #1009
- Dark theme for list view #1003

**Comment by dmfs** [comment]
What's your Android version? Tablet or phone?
I'll look int the code to show the progress gradient indicator.

**Comment by sp-icy** [comment]
Android 9. Phone. Thanks.

**Comment by dmfs** [comment]
This is probably caused by #1019

**Comment by dmfs** [comment]
fixed along with #1019

**Comment by sp-icy** [comment]
The new version (OpenTasks 1.4.2 from F-Droid) starts without crashing. Thank you.
