### ISSUE TITLE
Moving cursor left or right in checklists lines moves the cursor incorrect (with AnySoftKeyboard)

### ISSUE THREAD

**Issue by wired2051** [dmfs/opentasks#1024]
Since my update from v1.2.3 to v1.3.1 I have a problem with text input in the checklist lines. When I move the cursor left or right (with keys, not by finger tapping), the cursor jumps out of the checklist line or to the beginning of the checklist line (into line 1). 

The problem is reproducible. The title line and the location line are not affected.

I am using AnySoftKeyboard v1.10.1109, Android 7.

The problem is similar to Issue #664 from 2018 in my opinion but also occurs in single checklists lines.

**Comment by dmfs** [comment]
Sounds like the keys move the focus instead of the cursor position. I'll check that.

**Comment by dmfs** [comment]
Oh, I guess that may be caused by the TextMovementMethod which enables the clickable links.
