### ISSUE TITLE
Duplicate description of function

### ISSUE THREAD

**Issue by Valdnet** [dmfs/opentasks#1030]
The description of the features of the theme is duplicated (maybe on purpose):

![obraz](https://user-images.githubusercontent.com/47037905/112462774-bbfa0180-8d61-11eb-896d-cdaeacfc0a0f.png)

https://github.com/dmfs/opentasks/blob/1e95aa1c09824473d5ea8369e55f861a331baff3/opentasks/src/main/res/xml-v29/appearance_preferences.xml#L11
https://github.com/dmfs/opentasks/blob/1e95aa1c09824473d5ea8369e55f861a331baff3/opentasks/src/main/res/xml-v29/appearance_preferences.xml#L17

For "Follow system" there should be a description of the function more suited to the setting, for example: "Follow system is experimental and only partially implemented."

App:
OpenTasks 1.4.2

**Comment by Valdnet** [comment]
Changes added in #1029. Please merge 😉.

**Comment by dmfs** [comment]
Yeah, I was a bit lazy. The idea was that it's the same dark part that's incomplete when you enable "follow system". So the description made sense to me. However, I appreciate the fix.
