### ISSUE TITLE
Trouble with Import Project to Android Studio

### ISSUE THREAD

**Issue by arthurhenrique** [dmfs/opentasks#133]
I have some troubles to import this project to Android Studio.

Firstly, i have had download all of requirements, but when i run that project, 
the Messages Build Gradle show this.

Error:(29, 31) error: package android.support.v4.view does not exist
Error:(30, 41) error: package android.support.v4.view.ViewPager does not exist
Error:(353, 40) error: cannot find symbol class OnPageChangeListener
Error:(63, 9) error: cannot find symbol class OnPageChangeListener
Error:(66, 10) error: cannot find symbol class ViewPager
Error:(173, 27) error: cannot find symbol class ViewPager
Error:(185, 38) error: cannot find symbol class OnPageChangeListener
Error:(355, 3) error: method does not override or implement a method from a supertype
Error:(370, 3) error: method does not override or implement a method from a supertype
Error:(372, 17) error: cannot find symbol variable ViewPager
Error:(381, 3) error: method does not override or implement a method from a supertype
Error:Execution failed for task ':library:compileReleaseJava'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED

What i need to run this project?

thanks and sorry by my english.

**Comment by dmfs** [comment]
Did you import our fork of PagerSlidingTabStrip?  https://github.com/dmfs/PagerSlidingTabStrip
The original version may or may not work. Not sure if our changes are still relevant.
FYI: We're planning to migrate to Android Studio as well.

**Comment by arthur393** [comment]
Hello, Marten.
Let me to introduce to you,I really apreciate your work. And I think that your android project will help me on my college project. 

No, I didn't use your PagerSlidingTabStrip fork.
But now, I cloned and test in my local repository,  and show the same error message.

By the way, 
I downloaded the eclipse indigo with ADT 23.0.6, but when i import your project. The Console show me others errors messages. 
In files such ViewTaskFragment and styles there is some errors.
   - ViewTaskFragment.java 
   - styles.xml

How can I import this project on eclipse and make it's work?

Thank you, and sorry again by my english.

**Comment by dmfs** [comment]
Make sure you have included the following projects:

https://github.com/dmfs/xmlobjects (just put the latest jar into the libs directory)
https://github.com/dmfs/PagerSlidingTabStrip (linked as an Android library project)
https://github.com/dmfs/task-provider (linked as an Android library project)
https://github.com/romannurik/dashclock (the latest version should work well)

Also make sure you've added the support v7 library as an Android library and make sure you've installed the API 21 SDK.

FYI: we're planning to move to Android Studio and Gradle, that should make it much easier to build the app.

**Comment by arthur393** [comment]
Marten, 

I can't run your project in eclipse too, I really try in several times, and all of my tries 
it shows me several Message Erros.
I don't know if I did something wrong or if I forget some step.

By The Way,
I really hope you get move to Android Studio and Gradle.

P.S: If you have a step-by-step or a how-to install your project in eclipse, please, send to me,
I would be very thankful.

Sorry by my english.

**Comment by dmfs** [comment]
We're going to start porting the app to Android Studio right after 1.1.7 has been published but before we start working on 1.1.8.
So technically this will become a feature of 1.1.8

**Comment by arthur393** [comment]
Okay, Marten,
I'm very glad about this.

I have a doubt about the time, 
When you go to publish the *.7 and the *.8?

You have any idea about that?

**Comment by art1fa** [comment]
Any progress on this?

**Comment by dmfs** [comment]
Working on this. During the last weeks we've checked if there are any branches that we can or should merge first. Since we're going to change the project directory layout when we switch to Android Studio it might become difficult to merge them afterwards.

**Comment by dmfs** [comment]
Just finished the migration. All the dependencies are pulled in via Gradle/Maven now.
