### ISSUE TITLE
Please provide a changelog

### ISSUE THREAD

**Issue by jondo** [dmfs/opentasks#159]
Could you please maintain a changelog file or add some "what's new" info to the [release page](https://github.com/dmfs/opentasks/releases)? I would add the corresponding link to [the F-Droid database](https://f-droid.org/repository/browse/?fdid=org.dmfs.tasks).
That would give users (like me) a summary of "why to upgrade to the latest version" without having to dive into the commit messages.

**Comment by dmfs** [comment]
Um, yes we certainly can. We'll start doing so with the next release.

**Comment by jondo** [comment]
Great!
