### ISSUE TITLE
Due tab does not show tasks

### ISSUE THREAD

**Issue by borghal** [dmfs/opentasks#162]
I'm using the latest version of opentasks and sync with my owncloud 8.1.1 via DAVdroid. When I create tasks in a different client, they get synced and display correctly in the first tab of opentasks. However, the same tasks do not appear at all in the second tab sorted by due dates.

I can make them appear by opening tasks to edit them and save them without changing anything.

**Comment by dmfs** [comment]
Does that happen with all-day tasks too? It sounds as if DavDroid doesn't set the all-day flag to 0 when a task is not all-day. The "due" tab doesn't show tasks with a "null" (i.e. undefined) all-day flag.

**Comment by borghal** [comment]
You are right, after I switched to Caldav Sync everything works fine.

Thank you for your quick help!
Timm


Am Fr, 4. Sep, 2015 um 7:57 schrieb Marten Gajda 
<notifications@github.com>:

**Comment by dmfs** [comment]
great :-)

**Comment by rfc2822** [comment]
> It sounds as if DavDroid doesn't set the all-day flag to 0 when a task is not all-day. The "due" tab doesn't show tasks with a "null" (i.e. undefined) all-day flag.

At least it [should do so](https://github.com/bitfireAT/davdroid/blob/v0.8.4.1/app/src/main/java/at/bitfire/davdroid/resource/LocalTaskList.java#L321)…

**Comment by dmfs** [comment]
True, but only if a start date is set, not if the task has a due date only.

**Comment by rfc2822** [comment]
> True, but only if a start date is set, not if the task has a due date only.

Ah, ok, so an "all-day task" in terms of opentasks-provider is a task that has DTSTART or DUE (or both) set to a DATE value.

**Comment by dmfs** [comment]
Just like an all-day event has no time and timezone information, an all-day task has no time and timezone information either. I think that's the definition of an all-day task, i.e. the task has no specific (absolute) times.
It doesn't matter if only one of `DTSTART` and `DUE` or both are given (as long as they both have the same type when present).
