### ISSUE TITLE
Created list is not downloaded

### ISSUE THREAD

**Issue by agilob** [dmfs/opentasks#163]
I configured DavDroid to sync tasks from ownCloud, after first sync list of todos were downloaded, but I made some changes on ownCloud. One list was renamed and one added, changes from modified list were downloaded to android devices, but new list is not available. How can I download and sync it?

**Comment by dmfs** [comment]
Please direct this to the DavDroid team. OpenTasks is just the sync target. Synchronisation itself is performed by DavDroid in your case and only DavDroid can update any task lists.

**Comment by agilob** [comment]
Ok thanks!
