### ISSUE TITLE
Summary-less task should not be discarded when trying to save

### ISSUE THREAD

**Issue by untitaker** [dmfs/opentasks#164]
The other day I was creating a task and entered a lot of text into the description field, as some form of notetaking. When I saved the task, the app discarded everything I wrote because I forgot to specify a summary.

Instead of discarding the task, it should mark the summary field as invalid and refuse to exit and/or save, or simply insert a dummy value for the summary.

**Comment by dmfs** [comment]
Agreed. There is another option: We could just use the first line of the description or the first check list item if there is no description. If there is no description and no check list, we would still discard the task, since there is no use for a task without title, description or check list.

**Comment by untitaker** [comment]
First check list item as summary makes little sense to me, but I agree with the rest.

**Comment by dmfs** [comment]
Maybe we should automatically set the title to something like "untitled check list" if only a check list is present?!

**Comment by maulwuff** [comment]
How does this play with #127 ?

**Comment by dmfs** [comment]
Oh, good thing, we already implemented this. How could I forget about this one?

Anyway I just noticed a crash when testing #127. I will open a new ticket.

@untitaker which version did you use then? Doesn't #127 solve the problem?

The only difference is the "untitled check list" thing.

**Comment by dmfs** [comment]
@untitaker I'm considering this being fixed. If you still see a problem with 1.1.8 please open a new issue.
