### ISSUE TITLE
Update library versions in README.md

### ISSUE THREAD

**Issue by RealRancor** [dmfs/opentasks#165]
Hi,

just updating the app on f-droid an noticed that the README.md either contains no version info for some libs:

Color Picker -> No version
PagerSlidingTabStrip -> No Version

or a wrong version:

Dashclock 2.0 -> Only version 1.7 is available at https://github.com/romannurik/dashclock/releases

It would be great if the README.md contains all relevant version infos of the libs.

**Comment by dmfs** [comment]
we're planning to switch to Android Studio and use Gradle to manage dependencies. That should solve these issues. See #133

> Color Picker -> No version

Just use the latest commit.

> PagerSlidingTabStrip -> No Version

Use the latest version. We're planning to get rid of this with the next release.

> Dashclock 2.0 -> Only version 1.7 is available at https://github.com/romannurik/dashclock/releases

This refers to the API version. Use this:
http://mvnrepository.com/artifact/com.google.android.apps.dashclock/dashclock-api/2.0.0

> It would be great if the README.md contains all relevant version infos of the libs.

agreed. We'll fix that.

**Comment by RealRancor** [comment]
Thanks for the info. Was able to build 1.1.7 on f-droid, that versions should appear soon.

Looking forward to the move to gradle, that makes the build a lot easier.
