### ISSUE TITLE
Add support to Notes / Memo sync

### ISSUE THREAD

**Issue by MagicFab** [dmfs/opentasks#169]
I inquired about this [here](https://forums.bitfire.at/topic/812/memo-notes-in-caldav-sync-support), now wondering if it wouldn't be logical (and easier) to add support for it in OpenTasks?

**Comment by dmfs** [comment]
Well, tasks and journals/notes do have a lot in common, but still they are quite different concepts. In particular you want a different UI concept for both, e.g. usually you expect a task to get out of your view once completed, while there is no concept of "completion" for notes.

We're actually working on a separate app for notes. It will be a standalone open source notes app with a public interface for sync apps, just like OpenTasks but for notes. I think that's a better solution.
