### ISSUE TITLE
feature request: task in notification-drawer

### ISSUE THREAD

**Issue by kennyMC** [dmfs/opentasks#179]
add an option to view the tasks in the notification drawer like this app for calendar:
https://play.google.com/store/apps/details?id=de.steverohrlack.statusagenda

so it will be possible to have them on the lockscreen and you can have a quick look on open tasks.

**Comment by dmfs** [comment]
Interesting idea. Have you tried the pinned tasks feature though? It might cover a similar use case.

**Comment by kennyMC** [comment]
that feature fits my needs. just didn't noticed it yet.
