### ISSUE TITLE
Allow to change the list an existing task belongs to

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#18]
Just changing the list is not possible. The sync adapters would get out of sync if we just move the task to another list.

To implement this feature we have to copy the task to the new list and remove it from the old one. We have to do that in an atomic operation to ensure the consistency of the database. So this feature depends on transactions in dmfs/task-provider.

**Comment by Lykos153** [comment]
What about starting with a simple "copy to ..." feature?

**Comment by dmfs** [comment]
We actually found another (probably even better) way to implement this. We'll move the copy/delete logic to the provider, so the UI will be allowed to just change the list (instead of doing an atomic copy/delete operation).
That's possible now, because we've just refactored the provider part.

**Comment by dmfs** [comment]
Just finished this. All tests passed. Now we're testing if CalDAV-Sync handles this correctly. So far it looks good, though we had to change a few parts to handle recurrence exceptions the right way. 

Send us an email to get the test versions.
