### ISSUE TITLE
Update the end date when the start date is more recent

### ISSUE THREAD

**Issue by CLevasseur** [dmfs/opentasks#180]
If i set the start date of a task to 8th december and the end date to 8th december as well, and then change the start date to 10th december, the start date will not be updated (well in that case it will just take the end date, which is the same) because it will me more recent than the end date. Wouldn't it be more convenient that both the start/end date are set to 10th december instead ?

**Comment by dmfs** [comment]
you're right, that's probably the better way to handle that. Since should be an easy fix I'll add it to 1.1.8

**Comment by dmfs** [comment]
Done
