### ISSUE TITLE
Widget: Wrong task opened on click

### ISSUE THREAD

**Issue by CLevasseur** [dmfs/opentasks#189]
Sometimes the wrong task is opened when i click on a task on the widget, as you can see on the attached video. I can't tell why sometimes it works and why sometimes it does not.
I'm using OpenTask 1.1.7 and Android 6.0.1 on a Nexus 5

[2016_01_07_15_09_45.mp4.zip](https://github.com/dmfs/opentasks/files/81319/2016_01_07_15_09_45.mp4.zip)

**Comment by dmfs** [comment]
This has already fixed and it will be released with the upcoming version 1.1.8
