### ISSUE TITLE
Crash when saving a task and going to home screen

### ISSUE THREAD

**Issue by thesuperdavis** [dmfs/opentasks#192]
When you save a task, the dialog box "task created" appears for about 1s. When you go to the homescreen or to the recent apps before this dialog closes, the app crashes but the task is saved.

Logcat from the crash:
>E/AndroidRuntime(22354): FATAL EXCEPTION: main
E/AndroidRuntime(22354): Process: org.dmfs.tasks, PID: 22354
E/AndroidRuntime(22354): java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
E/AndroidRuntime(22354): 	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1365)
E/AndroidRuntime(22354): 	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1383)
E/AndroidRuntime(22354): 	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:636)
E/AndroidRuntime(22354): 	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:615)
E/AndroidRuntime(22354): 	at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:200)
E/AndroidRuntime(22354): 	at android.support.v4.app.DialogFragment.dismiss(DialogFragment.java:166)
E/AndroidRuntime(22354): 	at org.dmfs.tasks.QuickAddDialogFragment$1.run(QuickAddDialogFragment.java:470)
E/AndroidRuntime(22354): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(22354): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(22354): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(22354): 	at android.app.ActivityThread.main(ActivityThread.java:5310)
E/AndroidRuntime(22354): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22354): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(22354): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
E/AndroidRuntime(22354): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
W/ActivityManager(  830):   Force finishing activity org.dmfs.tasks/.TaskListActivity

**Comment by lemonboston** [comment]
@dmfs can this be closed now that #255 has been merged to staging?

**Comment by dmfs** [comment]
Yes. I expected it to be closed automatically. Looks like github didn't recognize the "Fix bug". Try just "fixes #..." next time.
