### ISSUE TITLE
Move task to another calendar

### ISSUE THREAD

**Issue by jkufner** [dmfs/opentasks#198]
When creating a new task, the name of a calendar is a drop down menu, which allows user to select calendar, where the task should be created.

When editing existing task, the name of a calendar is static label, so it is not possible to change calendar and therefore it is not possible to move task from one calendar to another. It would be nice if the calendar was editable even for existing tasks. Changing the calendar means that the task must be created (copied) into the newly selected calendar and then removed from previous calendar.

**Comment by dmfs** [comment]
That's already covered by #18 and will be released soon. We've decided to move the copy/delete logic into the provider part. That keeps the UI simple and makes the operation atomic.
