### ISSUE TITLE
Pinned completed tasks can be marked completed in the pin notification

### ISSUE THREAD

**Issue by real-or-random** [dmfs/opentasks#200]
Offering to mark a completed task completed just does not make sense.

Note that this is independent from #199, because you can always pin completed tasks manually (no matter whether they have been unpinned automatically or not).

Also, the notification should clearly indicate that the task is completed and should not display a due date.

**Comment by dmfs** [comment]
true, we need to update the pin notification for completed tasks

**Comment by lemonboston** [comment]
As I understand from other threads here, currently we don't want to automatically remove pinned notification when the task gets completed from the app, so it should stay there.
How should it look like in completed state?

**Comment by lemonboston** [comment]
I see now that upon completion the pin notification does get removed automatically actually. So this case is about when we pin an already completed task, if I get this right the second time.

**Comment by real-or-random** [comment]
Right. A second case is that a pinned task is completed via sync (#199).

**Comment by dmfs** [comment]
Correct. The pinned notification should respect the completed state of the task. So when a pinned task is completed via sync the notification should be updated, not removed.
I'm not 100% sure, but also I think that the task is still pinned when you swipe to complete.
