### ISSUE TITLE
no longer shows synced task lists

### ISSUE THREAD

**Issue by hazzl** [dmfs/opentasks#201]
Since version 1.1.8 the app no longer displays available synced task lists. Local lists seem to work OK, but are kind of pointless.

**Comment by dmfs** [comment]
Which Android Version are you running? Which sync App do you use? Is the sync account still present?
Is your device rooted?

**Comment by hazzl** [comment]
I'm running CM13 (based on Marshmallow) and I'm using your CaldavSync . The Syncaccount is present and the device is rooted.

**Comment by hazzl** [comment]
Never mind, things seem to be working again. Is it possible that lists are only shown after a reboot of the device?
