### ISSUE TITLE
Widget issue

### ISSUE THREAD

**Issue by oregszun** [dmfs/opentasks#202]
Hi,

the widget only show the title but no tasks. If i open the app the tasks are shown corretly. Sometimes the tasks show up in widget, but havent figured out yet when.

I face issue on both phones, cm12.1 and cm13 with Nova Launcher and as I remember Apex stil had.

**Comment by benedetto** [comment]
The widget does only show tasks that are currently active, i.e. that have no start date or a start date that lies in the past, but no tasks with a start date in the future. In the app itself, all tasks are shown independent of their status. Does this correspond to your situation?

**Comment by oregszun** [comment]
Hi, 

no, the widget does not show any task at all. I delete the widget,
readd, and works again for a while.

On 2016-02-12 12:21, benedetto wrote:

> The widget does only show tasks that are currently active, i.e. that have no start date or a start date that lies in the past, but no tasks with a start date in the future. In the app itself, all tasks are shown independent of their status. Does this correspond to your situation? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/dmfs/opentasks/issues/202#issuecomment-183284030

**Comment by dmfs** [comment]
Can you reproduce this with a different launcher?

**Comment by oregszun** [comment]
Nova and Apex both failed. I will try with built in trebuchet.

On 2016-02-12 15:31, Marten Gajda wrote:

> Can you reproduce this with a different launcher? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/dmfs/opentasks/issues/202#issuecomment-183352841

**Comment by oregszun** [comment]
Hi,

the same happend with default launcher. :(

Üdvözlettel:
Vukovics Mihály

**Comment by dmfs** [comment]
I see. Which widget are you using? The resizable or the fixed size one? Can you try to the other one? Maybe just one of them is buggy.

**Comment by oregszun** [comment]
I used the 4x4 one, now the 2x1, and seems to work!

**Comment by dmfs** [comment]
Great! So it's the large widget only. We'll check what's wrong.  Btw, are you on 1.1.8.2? I've fixed an issue like that recently.

**Comment by oregszun** [comment]
Hi,

yes, using the latest 1.1.8.2!

**Comment by dmfs** [comment]
This should be fixed in the staging branch and with the next release.
