### ISSUE TITLE
Installing opentasks after davdroid does not sync task lists

### ISSUE THREAD

**Issue by khartahk** [dmfs/opentasks#209]
I've un-installed open tasks then reinstalled them and now the app does not pick up the task lists. The calendar is working, the contacts are synced but the tasks are not showing. If I reinstall davdroid i can set the task lists but that's the only time when I can set them. Am I missing something in davdroid or is there a bug in opentasks?

**Comment by khartahk** [comment]
Found the answer to this one - it's a DAVdroid missing an option to resubscribe or add new calendars after the setup. You have to remove and re-add the account. Not perfect but workable. If only it would not loose the contact images when I do that :)

**Comment by jkufner** [comment]
Contact images should be synced to your CardDAV server. If not, it is a bug.

**Comment by khartahk** [comment]
They are synced. But if I delete the account and re-add it the images disappear. At least the ones connected to the contacts I starred. I don't know if those are the only ones but this happens. Once I re-add the images until I remove the DAVdroid account the images stay synced.
