### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page; 1.1.8.2

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [dmfs/opentasks#210]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 1.1.8.2.

**Comment by dmfs** [comment]
Please direct this request to the F-Droid team. We can't do anything about that.

**Comment by locutis-of-borg-1999** [comment]
That is not what other dev's report.  They were glad to have been informed.  

https://f-droid.org/manual/html_node/Changelog.html#Changelog
