### ISSUE TITLE
Check overflow menu handling in ViewTaskFragment.

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#220]
Apparently it's possible to delete a task in 2 pane mode even though there is no task. Otherwise #211 would be impossible (unless that is caused by a race condition).

**Comment by lemonboston** [comment]
Yes, I could reproduce it:
In 2 pane mode delete a task from the bottom of a list, the detail view keeps the deleted task title and the action bar.
Any action from the action bar (complete, pin, edit, delete) result in crash (NPE for ContentSet).

**Comment by lemonboston** [comment]
This cause by incorrect handling of ViewTaskFragment.loadUri(null) which is called when the detail view should display empty content.
Both the menu part and the title part are not handled correctly.
Menu could be fixed easily, the title is not that obvious.

Your (@dmfs) idea on this:

> I consider setting values to null to clear any output being bad design. Why not just hide the container or the entire fragment if there is no content to show? Or even better, replace the entire Fragment by an "EmptyDetailsFragment". The "EmptyDetailsFragment" could show some hint like "No task selected" or if there are no tasks at all replace it by a "NoTasksFragment" that says something like "Relax and sit back, there are no tasks. Tap here to add a task.".
> We probably can use the same message if there are no visible tasks (because all have been completed). We should work out the details in which case, which message should be shown.

This would be clearly better in my opinion as well.
Should we create a separate enhancement issue for this?

**Comment by dmfs** [comment]
Yes, please open a new issue for that.

**Comment by lemonboston** [comment]
#259 has been opened for the empty task detail fragment. When that is completed, this can be closed as well.
