### ISSUE TITLE
Small bug: task_completed displays time +1h compared to editing view

### ISSUE THREAD

**Issue by biolauri** [dmfs/opentasks#224]
After completing a task, the detail view shows an incorrect completion time: If I complete the task today at *13:00 (1 pm)* (by editing the task), it displays *14:00 (2 pm)* at the detail view.

## Time zones have no effect
I think, the time zone doesn't matter, because the same happens when changing the tasks time zone to *GMT*. Preferably, I use *GMT+1* (both as phone and tasks standard).

## Calendar provider has no effect 
The problem occured in my tasks synced with OwnCloud as well as the Local tasks provided by this tasks app.

---

PS: Thanks for this great app! :+1:

**Comment by dmfs** [comment]
I can see the problem. There is a discrepancy between the completed date in the editor and in the details view. It's probably related to the time zone offset of your device.

**Comment by dmfs** [comment]
The problem is that `completed` is modeled without a local timezone but always in UTC. So the editor always shows the completed time in UTC, whereas the details view shows it in local time.

**Comment by dmfs** [comment]
Fixed in staging.
