### ISSUE TITLE
Opentasks/dmfs crashes when termux-app/termux 0.31 is installed

### ISSUE THREAD

**Issue by rudi123** [dmfs/opentasks#228]
The chrash occures when trying to edit a task. With version 0.30 everything is fine. There is also an error report at the termux-app/termux project.

**Comment by rudi123** [comment]
Here is the link to termux.

https://github.com/termux/termux-app/issues/68

**Comment by dmfs** [comment]
Please give a more detailed error description. What exactly do you do to trigger the crash?
How does it crash? Can you provide any stack trace or log?

**Comment by rudi123** [comment]
Hello

The termux developer has provided a new version already, but it is not online in the fdroid store for now. I respond to you after i have tried out the new version.

The problem occurs right after installing termux. After that when i am trying to edit a task entry opentasks crashes.

Sadly i cannot provide you any logs.

Thanks in advance

**Comment by rudi123** [comment]
Hello

The problem is gone with version 0.32 of Termux.

Happy easter!!
