### ISSUE TITLE
Completed tasks disappearing

### ISSUE THREAD

**Issue by ThePreviousOne** [dmfs/opentasks#229]
Each time I complete a task, or set its status to done, it goes away. I would like/expect them to show up on the "Task progress" tab under "Done", Am I missing something or is this a bug?

**Comment by wweich** [comment]
To see completed tasks, check the "show completed tasks" option in the menu.

**Comment by dmfs** [comment]
As @wweich stated, completed tasks are hidden by default. But you can change this setting for each tab.
We probably can show completed tasks by default on the task progress tab.

**Comment by alexander-alzate** [comment]
That setting is set per view. But I think that in the Task Progress view it shouldn't be hidden by default. I mean, it doesn't have sense to have a Progress category "Done" when nothing is going to be shown unless you explicitly set the option.
