### ISSUE TITLE
every created task is duplicated

### ISSUE THREAD

**Issue by sativouf** [dmfs/opentasks#232]
Hi,

For the past week or so, every time I create a task on my caldav server through the app, it shows twice after a short while or if I hit refresh.
It is created only once on the server, and another client (via thunderbird) shows only one task as well.
If I go to "tasks due", the correct tasks are displayed under "Someday".
If I delete the duplicate (second item), "tasks due"/"Someday" does not show it anymore, server marks the task as completed, but the other duplicate still shows up in the task list of the app.
If I delete the first item (and leave the duplicate untouched), "tasks due"/"Someday" still shows it up, server marks the task as completed, and it still shows up in the task list of the app.
Also, when deleting the first occurence, the second occurence disappears after a refresh.

I tried reinstalling the app / clearing cache + app data.

**Comment by sativouf** [comment]
This is not an opentasks issue, but a bug underneath (caldav-sync ? Android calendar storage ?), since I have the exact same behavior when creating a calendar event.

**Comment by dmfs** [comment]
What kind of server do you sync to? Sounds like a URL encoding issue to me. Please contact me by email. In the meantime please enable "Use WebDAV Method" in the account settings. That should help until the issue has been resolved.
