### ISSUE TITLE
Add option for making tasks recurring

### ISSUE THREAD

**Issue by craftyguy** [dmfs/opentasks#233]
Some tasks should be recurring, but there's currently not an option to indicate that they are!

**Comment by PanderMusubi** [comment]
Aren't you better off adding these to your calendar? See bottom left in https://en.wikipedia.org/wiki/Getting_Things_Done#/media/File:GTDcanonical.png

**Comment by craftyguy** [comment]
If you subscribe to one man's interpretation of what it takes to be productive, then I guess?

 Then again, there are apps (google now, recurrence, outlook tasks, etc) that allow setting up recurring tasks. I use these on other platforms and it works well, hence my request for this feature.

**Comment by PanderMusubi** [comment]
It is indeed only a way to do that. You have a valid feature request but at one point, I think, we should not duplicate all calendar functionality.

**Comment by skjnldsv** [comment]
Same here! There are things that should remain as "tasks" just for the purpose of these tasks.
Like for example cleaning the floor (stupid example). It is clearly a task, and should be done every week.
Is there a possibility for now to set a task as "to be done every x time"? 

Thanks for your beautiful apps (cal&card sync pro and opentasks)!

**Comment by dmfs** [comment]
This is now tracked under #462
