### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by colegota** [dmfs/opentasks#236]
I just installed 1.1.8.2 from Fdroid and notice that just a few strings are show in Spanish while at the project the file opentasks/opentasks/src/main/res/values-es/strings.xml it's completely translated.

Only can see in Spanish the strings at Task due screen, the main menu, and the visible_task_lists and synced_task_lists strings.

**Comment by dannycolin89** [comment]
Some strings are missing in the spanish translation file. There's only 117 lines compared to 259 lines in the english one.

**Comment by colegota** [comment]
And what it's the way to work? Usually we have a copy of English file with full lines in both original and translation.

I can translate it, just need to know how. So do I merge both files?

**Comment by dannycolin89** [comment]
You need to :
1. Fork this repository
2. Copy paste the missing lines in the spanish file from the english file
3. Translate those lines you just add to the spanish file
4. Do a pull request

That's basically what I did

**Comment by dmfs** [comment]
@dannycolin89 is right. That's the preferred way of doing that. Ideally you keep the string order the same. Optionally you can send us the file so we include it.

**Comment by colegota** [comment]
Will try to find out some time to follow the full process. Sometimes I collaborate in translations but all the sentences are in a unique file...
Keep you informed.

**Comment by colegota** [comment]
Did it!
Hope pull request was OK because it's the firs time I did it. :)
Have some doubts while translation that maybe can be fixed once I can test it at my phone.

**Comment by dmfs** [comment]
Looks good on a first glance. Just one change request for now: Please don't write words in capitals (i.e. ACEPTAR & CANCELAR), since capitalization is done by the UI if necessary. Actually these two words shouldn't be in the strings after all, because Android already provides translations for these. Not sure why they are still in there

**Comment by colegota** [comment]
OK, but they are in capitals at original current English version.

    <string name="task_list_selection_ok">OK</string>
    <string name="task_list_selection_cancel">CANCEL</string>

**Comment by colegota** [comment]
Did changed at my file. Don't know if need to close old pull request and create a new one. Please give me directions.
Thanks!

**Comment by dannycolin89** [comment]
No, you don't need to. Every commits you do on your master branch in your fork will be added to the pull request.

(see this :  https://github.com/dmfs/opentasks/pull/244/commits)

Oh and congrats for your first pull request :) !

**Comment by dmfs** [comment]
This is in staging and well be released shortly.
