### ISSUE TITLE
Open task after storing it

### ISSUE THREAD

**Issue by jkufner** [dmfs/opentasks#254]
I found anoying usability problem.

Curent state:
1. Creaate a task
2. Hit save button
3. Task is somewhere deep in the list

Better way:
1. Create task
2. Hit save button
3. Task opens, it is possible to edit it or pin it or whatever
4. Hit back button to get to the list

So the point is to open the newly saved task, because otherwise it is difficult to modify or pin the new task.

**Comment by dmfs** [comment]
Got your point. I guess that makes sense. We'll take care of it.

**Comment by lemonboston** [comment]
Should this be the behavior when saving from the quick _Add task_ dialog and the full _Create_ screen as well?

**Comment by lemonboston** [comment]
Submitted pull request for the _Create_ screen (editor) case.
