### ISSUE TITLE
Reminder without vibration

### ISSUE THREAD

**Issue by rampisi** [dmfs/opentasks#267]
Please make it possible that the vibration can be turned off for the reminder.

**Comment by dmfs** [comment]
released in 1.1.10

**Comment by yaomtc** [comment]
What happened to this? I don't have this option in 1.1.20.

**Comment by dmfs** [comment]
@yaomtc which Android version do you use? Since Android 8 we rely on Android's stock notification settings which should provide you with an option to disable vibration.

**Comment by yaomtc** [comment]
LineageOS 16 (Android 9), which apparently moved the vibrate setting into Privacy Guard. Huh. Well, now I know!
