### ISSUE TITLE
Enahncement Request: Support for Tags (owncloud/Nextcloud)

### ISSUE THREAD

**Issue by aproposnix** [dmfs/opentasks#276]
In owncloud/Nextcloud tasks, I'm able to set tags.  it would be nice to have that same feature in Opentasks.

**Comment by viharm** [comment]
+1

I would like this too. I think these are referred to as "categories" in Nextcloud

**Comment by nicorikken** [comment]
Support for categories (tags) was already on the roadmap [#14](https://github.com/dmfs/opentasks/issues/14) so this is a duplicate issue.

**Comment by wToad** [comment]
@dmfs you can close this issue I guess
