### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#279]
Many of the current feature requests require a proper settings screen.

**Comment by lemonboston** [comment]
An earlier note about this story from @dmfs:

> Regular PreferenceFragment, on Android 2.x it's not supported, just disable it.
> Add to settings:
> - show notification or not
> - notification sound (maybe allow to set independently for start and due)
> - vibrate on notification or not

**Comment by lemonboston** [comment]
@dmfs I've submitted a PR https://github.com/dmfs/opentasks/pull/389 with a Settings screen containing only "show notification or not".
Is continuing with this a priority now and if so what should be the next settings to add?

**Comment by dmfs** [comment]
We've received a couple of requests to change the notification sound (#124) and disable notification vibration (#305).
These should be next.
