### ISSUE TITLE
Notification remains if task is deleted remotely

### ISSUE THREAD

**Issue by korelstar** [dmfs/opentasks#281]
Steps to reproduce:
1. create a task
2. sync the task with a server (I used DAVdroid and ownCloud)
3. trigger a [notification](https://developer.android.com/guide/topics/ui/notifiers/notifications.html), e.g.`Task starts today`, `Task due today` or pin the task
4. delete that task remotely
5. trigger or wait for synchronization

Issue:
The notification for that task is still there, although the task is deleted. When tapping on the notification, the task details activity is opened, but there is no text in it and buttons do not work.
Notifications of type `Task starts today`, `Task due today` etc. disappear then. However, if the deleted task was pinned, the notification still remains and it is not possible to remove it. Only after some hours, the pin-notification disappeared without further intervention.

**Comment by dmfs** [comment]
This should have been fixed by #780.
