### ISSUE TITLE
Misspelling of `constraint` in package `org.dmfs.tasks.model`

### ISSUE THREAD

**Issue by korelstar** [dmfs/opentasks#307]
I'm currently working on enhancing the setting of `DTSTART` and `DUE` (i.e. providing a default value which respects the constraint `DUE>DTSTART`; keep the duration `DUE-DTSTART` of a task if `DUE` or `DTSTART` needs to be shifted due to a violated constraint) and I will make a respective pull request.

However, while studying the code, I found that the word `constraint` is misspelled at different locations:

- package name `org.dmfs.tasks.model.contraints`
- method name and parameter `org.dmfs.tasks.model.adapters.FieldAdapter.addContraint(AbstractConstraint<Type> contraint)`

Is this intended? If not, I would propose to refactor these occurrences. I can do this in my upcoming pull request.

**Comment by dmfs** [comment]
I guess that goes back to when Eclipse didn't support spell checking of Java identifiers, so no one noticed it. Yes, it should be renamed.
