### ISSUE TITLE
Search delivers wrong Items in result list

### ISSUE THREAD

**Issue by Tschukis** [dmfs/opentasks#322]
Tested on android 6 in german language.
Absolute nonsens is coming up whenever I try to find something.

**Comment by dmfs** [comment]
Hmm. I see. That's probably an issue of using "TASK_ID" vs. "INSTANCE_ID". Which means the search engine finds the correct tasks, but returns the wrong ID or the UI components uses the ID on the wrong table.

**Comment by dmfs** [comment]
fix finally merged in PR #330
