### ISSUE TITLE
Folders and Subfolders

### ISSUE THREAD

**Issue by jensschulz** [dmfs/opentasks#339]
I noticed that the synchronization of the folder list is only done once after installation. When I change folder names or add new folders on the server, they are not synchronized and don't even show up in the "folders to synchronize" panel.
Furthermore, the app never (not even after installation) synchronizes subfolders. I use zimbra to create my tasks and there, subfolders are allowed. It seems like the app is missing this feature.

I would greatly appreciate these two features! Thank you!

**Comment by dmfs** [comment]
Note that subfolders are not supported by the CalDAV protocol. Zimbra is not standards compliant in that regard. They should flatten the tree structure when exposing task folders via CalDAV.

Regarding the folders not being updated, that's most likely an issue with the sync app not with OpenTasks.

**Comment by jensschulz** [comment]
I suspected those issues might also be related to either sync or zimbra, thanks for clarifying that. I use your caldav app for synchronization, so should I write a support request? Thank you for your help!

**Comment by dmfs** [comment]
Yes, please reach out to our support team. Thanks!
