### ISSUE TITLE
Make widged scrollable

### ISSUE THREAD

**Issue by tillschaefer** [dmfs/opentasks#34]
It would be nice to make the widget scrollable. If more tasks are present than the widget can show, it becomes useless as one need to open the application to see all tasks. GTasks has two ways two browse through the tasks inside the widget. i think we should adapt this behavior.
1. provide some paging with some errors in the top bar if the android version is not capable of scroll bars inside widgets
2. provide a scroll bar which let you scroll through all your tasks

**Comment by dmfs** [comment]
I think this is no longer relevant. We don't support Android 2.x any more.
