### ISSUE TITLE
Add code style settings to git

### ISSUE THREAD

**Issue by lemonboston** [dmfs/opentasks#345]
`.idea/codeStyleSettings.xml` is currently ignored, so we don't have a common code style in the project.
We can add dmfs latest version but we have make sure not to use it inside existing classes and at commit time before all files are updated at once, cause it may make diffs more difficult to review.

**Comment by copynpaste** [comment]
Why should we use JetBrains specific stuff when there is Editorconfig, which is supported in more IDEs?

**Comment by dmfs** [comment]
@copynpaste didn't know about Editorconfig. Nice! You're right, it's probably better to use this.

**Comment by dmfs** [comment]
We went without EditorConfig for now. The EditorConfig file created by Android Studio was fairly basic and didn't account for various settings we use. Also the resulting format was actually different in a few cases.
We'll probably look into this again.
