### ISSUE TITLE
Add support for recurring tasks

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#367]
@dmfs commented on [Wed Jun 19 2013](https://github.com/dmfs/opentasks-provider/issues/1)

The task provider needs support for recurring tasks. That is, the instances of a task with `RRULE` or `RDATE` values have to be expanded and stored in the instances table.

If a task has neither a `DTSTART` nor a `DUE` value no instances get expanded.

A second table should contain the completed and the upcoming incomplete instance of a series of tasks. This table doesn't exist yet and needs to be created.

There already is a library to evaluate any `RRULE` values: https://github.com/dmfs/lib-recur

---

@dmfs commented on [Wed Nov 12 2014](https://github.com/dmfs/opentasks-provider/issues/1#issuecomment-62692459)

Moved to 1.2

---

@Lykos153 commented on [Sun Sep 13 2015](https://github.com/dmfs/opentasks-provider/issues/1#issuecomment-139879276)

Is there an ETA for this feature?

---

@dmfs commented on [Mon Sep 14 2015](https://github.com/dmfs/opentasks-provider/issues/1#issuecomment-140031805)

Sorry, no ETA. We're working on that, but at present we're quite busy with paid work.
The goal is to finish it before the end of this year.

---

@languitar commented on [Sat Nov 28 2015](https://github.com/dmfs/opentasks-provider/issues/1#issuecomment-160325031)

I'm also interested in this.

---

@jpthorn01 commented on [Sun Nov 13 2016](https://github.com/dmfs/opentasks-provider/issues/1#issuecomment-260202363)

Do you guys need help implementing this? This would be a great feature to add.

**Comment by skjnldsv** [comment]
Hello, any news on this?

**Comment by dmfs** [comment]
This is now tracked under #462
