### ISSUE TITLE
Use template engine for creating the shared task text

### ISSUE THREAD

**Issue by lemonboston** [dmfs/opentasks#372]
The composition of the text when sharing a task has been implemented with 'manual' concatenation logic, it would be better to use a template engine for it.
See https://github.com/dmfs/opentasks/pull/368#issuecomment-313523823 as well.

**Comment by dmfs** [comment]
@lemonboston please check if the changes in codeka/carrot#1 do the trick

**Comment by lemonboston** [comment]
Yes, it works but I had to still fork it to add
```groovy
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
```
because by default jitpack builds it with Java 8 and that can't be imported.

I also added a custom carrot `ResourceLocater` to look up raw Android resource:
https://github.com/dmfs/opentasks/blob/5cfddb6574b64ff41e9acfaf0a159ec3f558a077/opentasks/src/main/java/org/dmfs/tasks/share/RawIdResourceLocator.java#L37-L37
Usage in:
https://github.com/dmfs/opentasks/blob/5cfddb6574b64ff41e9acfaf0a159ec3f558a077/opentasks/src/main/java/org/dmfs/tasks/share/CarrotShareTaskText.java#L53-L53

So there is this branch 'mx/372-template-engine-for-share' with working code but they are just initial commits, I will continue with it and review changes there later.

**Comment by lemonboston** [comment]
@dmfs I leave it on hold until you confirm to go ahead with implementation.
The fork is here: https://github.com/lemonboston/carrot
An option may be to add a gradle task to the source project to create a jar with Java 7, to avoid having to maintain a fork.

**Comment by lemonboston** [comment]
I am not sure if it's worth keeping a fork of carrot which adds those two compatibility lines to build.gradle and import with jitpack, or it's simpler if we just build the jar by checking out the project and adding those lines.
For now I move on with latter, so I removed my fork and added the jar to the project with a note .txt about how to build it. (branch `mx/372-template-engine-for-share`).

**Comment by dmfs** [comment]
We certainly won't maintain a fork, so ideally we create a PR to get our changes upstream. That however requires to "fix" the tests to work with Java 7.
