### ISSUE TITLE
Search bug

### ISSUE THREAD

**Issue by shtrom** [dmfs/opentasks#374]
I just noticed this this morning (irronically, looking for a task to remind me to open another issue with opentasks).
![screenshot_20170709-145521](https://user-images.githubusercontent.com/160280/27991914-277c3790-64c9-11e7-9570-4efed22c990e.png)

I was looking for an issue with `Github` in the title, and no result showed up. However, the result I was looking for showed up in a previous search that I made `Jtag`. Deleting that search, and recreating it with the same search string led to the same situation, as shown in the screenshot. There is no `Jtag` string anywhere in that task.

Nothing showed in the logcat (filtering for `tasks`) when I cleared all searches and re-added both the above.

Is there anything I can do to debug further

**Comment by dmfs** [comment]
This has been fixed with #322 and released with 1.1.9 which is currently being rolled out on Google Play (I've just set it to 50%). Please reopen if this is still an issue with 1.1.9.

**Comment by shtrom** [comment]
Ah, I'm still on 1.1.8.2 from F-Droid. I'll see when it gets updated. Cheers.
