### ISSUE TITLE
Please update changelog for vetsion 1.1.9

### ISSUE THREAD

**Issue by aelmahmoudy** [dmfs/opentasks#375]
The changlog file needs to be updated with an entry about changes in version 1.1.9

**Comment by dmfs** [comment]
I've just added release notes: https://github.com/dmfs/opentasks/releases/tag/1.1.9
I'd prefer to maintain these and get rid of the change log file if there are no objections.

**Comment by dmfs** [comment]
I'll migrate the `CHANGELOG` entries to GitHub and remove the file to avoid confusion.
