### ISSUE TITLE
Update notification on changes

### ISSUE THREAD

**Issue by noresistence** [dmfs/opentasks#400]
Notifications don't get updated, when the corresponding task is changed.

__Reproduction__

Add a task that is due today. A notification appears. Now do not click on the notification. from the tasks app:

1. change title
2. change the due date to tomorrow
3. delete the task

__Expected behaviour__

1. Notification changes title
2. Notification disappears
3. Notification disappears

__Observed behaviour__

Notification does not change at all.

**Comment by dmfs** [comment]
updating/removing notifications is now implemented
