### ISSUE TITLE
Widget not showing syncted CalDav tasks when app closed, & does't refresh when opened.

### ISSUE THREAD

**Issue by patricksettle** [dmfs/opentasks#405]
The widget does not show synced CalDAV data when app is closed. After opening the app the widget data is not refreshed.

Removing the widget, then opening the app will display the synced CalDAV data.  Additionally, I noticed that the app doesn't seem to really "sync" as in hold the CalDAV data between sync events, once you close the app, the data is gone until the app syncs again, which I'd guess is the root cause of the disappearing data in the widget.

Moto 5 Plus
Android 7.0
OpenTasks 1.1.9
DAVdroid 1.6.5-play

**Comment by maximevaillancourt** [comment]
I'm getting the exact same behavior on the following setup : 
- OnePlus 5
- Android 7.1.1
- OpenTasks 1.1.9
- DAVDroid 1.6.5-ose

Appears to be related to #404.

**Comment by maximevaillancourt** [comment]
After doing `logcat | grep org.dmfs.tasks` in an adb shell, I managed to log what happens when I close the app, then open it again (after which the tasks disappear from the widget).

Here's me closing the app:

```
08-15 22:46:34.718  1526  1570 I ActivityManager: Killing 12899:org.dmfs.tasks/u0a114 (adj 900): remove task
08-15 22:46:34.775  1526  2396 W InputDispatcher: channel 'c072942 org.dmfs.tasks/org.dmfs.tasks.ViewTaskActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-15 22:46:34.775  1526  2396 E InputDispatcher: channel 'c072942 org.dmfs.tasks/org.dmfs.tasks.ViewTaskActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
08-15 22:46:34.777  1526  2396 W InputDispatcher: channel '802257f org.dmfs.tasks/org.dmfs.tasks.TaskListActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-15 22:46:34.777  1526  2396 E InputDispatcher: channel '802257f org.dmfs.tasks/org.dmfs.tasks.TaskListActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
08-15 22:46:34.785  1526  3846 I WindowManager: WIN DEATH: Window{c072942 u0 org.dmfs.tasks/org.dmfs.tasks.ViewTaskActivity}
08-15 22:46:34.785  1526  3846 W InputDispatcher: Attempted to unregister already unregistered input channel 'c072942 org.dmfs.tasks/org.dmfs.tasks.ViewTaskActivity (server)'
08-15 22:46:34.785  1526 18785 D EmbryoManager: prepare org.dmfs.tasks
08-15 22:46:34.785  1526 18785 D ActivityManager: get process top duration : org.dmfs.tasks, duration : 0
08-15 22:46:34.788  1526  3943 I WindowManager: WIN DEATH: Window{802257f u0 org.dmfs.tasks/org.dmfs.tasks.TaskListActivity}
08-15 22:46:34.788  1526  3943 W InputDispatcher: Attempted to unregister already unregistered input channel '802257f org.dmfs.tasks/org.dmfs.tasks.TaskListActivity (server)'
```

Then, a few seconds later, here's what happens when opening the app:

```
08-15 22:46:47.898  1526  1569 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.dmfs.tasks/.TaskListActivity (has extras)} from uid 10102 pid 18732 on display 0
08-15 22:46:47.903  1526  1569 D ActivityTrigger: activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{fe2ec0 org.dmfs.tasks}
08-15 22:46:47.903  1526  1569 E ActivityTrigger: activityStartTrigger: not whiteListedorg.dmfs.tasks/org.dmfs.tasks.TaskListActivity/611
08-15 22:46:47.906  1526  1569 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{fe2ec0 org.dmfs.tasks} is now in focus and seems to be in full-screen mode
08-15 22:46:47.906  1526  1569 E ActivityTrigger: activityResumeTrigger: not whiteListedorg.dmfs.tasks/org.dmfs.tasks.TaskListActivity/611
08-15 22:46:47.912  1526  3920 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{fe2ec0 org.dmfs.tasks} is now in focus and seems to be in full-screen mode
08-15 22:46:47.912  1526  3920 E ActivityTrigger: activityResumeTrigger: not whiteListedorg.dmfs.tasks/org.dmfs.tasks.TaskListActivity/611
08-15 22:46:47.912  1526  3920 D EmbryoManager: Embryo claimed. org.dmfs.tasks, pid=20653
08-15 22:46:48.023  2682  2682 D SystemServicesProxy: getRecentTasks: org.dmfs.tasks, 144
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: error inflating model for at.bitfire.davdroid
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: org.dmfs.tasks.model.ModelInflaterException: No model definition found for package at.bitfire.davdroid
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: 	at org.dmfs.tasks.model.XmlModel.inflate(XmlModel.java:289)
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: 	at org.dmfs.tasks.model.Sources.getAccounts(Sources.java:180)
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: 	at org.dmfs.tasks.model.Sources.<init>(Sources.java:142)
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: 	at org.dmfs.tasks.model.Sources.getInstance(Sources.java:84)
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: 	at org.dmfs.tasks.utils.AsyncModelLoader.doInBackground(AsyncModelLoader.java:73)
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: 	at org.dmfs.tasks.utils.AsyncModelLoader.doInBackground(AsyncModelLoader.java:36)
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: 	at java.lang.Thread.run(Thread.java:761)
08-15 22:46:48.078  1526  1641 I ActivityManager: Displayed org.dmfs.tasks/.TaskListActivity: +165ms
08-15 22:46:48.090 20653 15188 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:46:48.091 20653 15188 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:46:49.358  2682  2682 D SystemServicesProxy: getRecentTasks: org.dmfs.tasks, 144
```

Then, here's what I get:

```
08-15 22:47:35.565 14751 15213 I davdroid: [syncadapter.SyncAdapterService] org.dmfs.tasks sync of Account {name=[redacted], type=bitfire.at.davdroid} has been initiated
08-15 22:47:35.632 20653 20664 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:35.635 20653 15188 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:35.665 20653 20665 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:35.666 20653 15188 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:35.692 20653 15216 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:35.692 20653 15188 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:37.042 14751 15213 I davdroid: [syncadapter.TasksSyncManager] Downloading 120 tasks (30 at once)
08-15 22:47:37.280 20653 20664 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:37.281 20653 15188 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:37.829 20653 20664 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:37.830 20653 15188 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:38.335 20653 20665 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:38.336 20653 15188 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:38.647 20653 20664 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:38.648 20653 15188 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:38.921 20653 15216 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:38.925 20653 15188 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:39.289 20653 15216 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:39.290 20653 15188 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:39.707 20653 15217 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:39.713 20653 15188 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
08-15 22:47:40.072 20653 15221 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
...
```

ContentResolver doesn't seem to like the URIs.

**Comment by dmfs** [comment]
There doesn't seem to be anything unusual in the logs.

```
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: error inflating model for at.bitfire.davdroid
08-15 22:46:48.029 20653 15193 E org.dmfs.tasks.model.Sources: org.dmfs.tasks.model.ModelInflaterException: No model definition found for package at.bitfire.davdroid
```
means that DavDroid doesn't provide a task model file. In this case OpenTasks just falls back to a default model, so this is nothing to worry about.


The URI error is known and not a serious issue. 
```
08-15 22:47:37.830 20653 15188 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
```
It just means that the ContentProvider returned an error when the system was trying to resolve the authority URI. The CalendarProvider did (or maybe still does) the same.
We tried to fix it in the past, but it had some side effects so we didn't change it back then.

**Comment by M-r-A** [comment]
Same issue
Galaxy S6
Android 7.0
OpenTasks 1.1.9
DAVdroid 1.6.5-play

When i open the app i see the counter of remote list: updating from 0 to real number of tasks in 2 tasks/sec.

**Comment by dmfs** [comment]
please check if the solution for #404 fixes this as well (in short: grant the "Contacts" permission in the device setting).

**Comment by M-r-A** [comment]
It works...

**Comment by obama** [comment]
i have granted contacts too but i only get displayed the local list in the widget.

**Comment by patricksettle** [comment]
That does seem to be a workaround, giving access to Contacts... However, I call it a work around, because the app can clearly pull the tasks without the Contacts permissions when opening the application directly...and if it can do that then why not the widget as well?

I bring this up, because it's hard to justify giving elevated permissions when they don't seem to be truly necessary.

**Comment by dmfs** [comment]
The app doesn't need the contacts permission at all (there is no code which tries to access your contacts).

That being said, granting access to the "Contacts" permission group is (currently) the (only) solution and not a workaround (at least not a workaround for an issue in the app). The problem here is Android. Google, in its great wisdom, has decided to put the `GET_ACCOUNTS` permission into the `CONTACTS` permission group (see https://developer.android.com/guide/topics/permissions/requesting.html#permission-groups). So when an app asks the user to grant the `GET_ACCOUNTS`  permission Android will prompt you to grant the "Contacts" permission. This is the bug report of this madness: https://issuetracker.google.com/issues/37065963

The app needs `GET_ACCOUNTS` to read the list of user accounts and remove orphaned task lists when the respective account has been removed, otherwise the lists and all data would still be in the app after you've deleted an account. That's the only reason. If the app doesn't have this permission, it will only see its own accounts (which is an empty list) and remove every list belonging to any account (except for the local lists). That's why the lists disappear from the app and widget.

@obama you need to recreate the widget, because it stores the list ids of the lists you selected. When the lists are recreated they get new list ids, so the "old" widget doesn't show them.

**Comment by dmfs** [comment]
As a matter of fact, the proper fix will be to check and request the `GET_ACCOUNTS` permission when you start the app. Unfortunately this will show a "Grand access to **Contacts**" prompt, so we'll have to explain this stupidity up front.
At present it's not clear to me how we can avoid this prompt when a user uses the app without sync adapter, because in that case we don't need the `GET_ACCOUNTS` permission. Maybe we only show a notification when a list has been added by a sync adapter.

**Comment by patricksettle** [comment]
I understand the Google stupidity behind the Contacts prompt for `GET_ACCOUNTS` I was just pointing out that even without contacts access granted, when I open the app the list populates. It's able to operate without the being granted access to Contacts.  

So I was more wondering why it's able to function when I open it but not the widget, as it makes me wonder that there may be a way to avoid the Google stupidity all together. Not being super familiar with the codebase... so I tottaly understand if there's some obvious reason for this which doesn't help the widget functionality (and if so sorry for the noise), but wanted to highlight that without Contacts granted the app _seems_ to be working, although looks like it has to refresh the task list each time it's relaunched, as opposed to using cached data.

To be clear what I am experiencing is this:

Moto 5 Plus
Android 7.0
OpenTasks 1.1.9
DAVdroid 1.6.5-play

**WITHOUT Contacts Access Granted:**
- App functions as expected
- all lists are displayed
- tasks are synced (add/remove) 
- at app launch, initially shows that each list has 0 tasks, but then populates (the list themselves are already there)
- widget populates initially, but once app is closed out and re-opened widget is blank

**WITH Contacts Access Granted:**
- App functions as expected
- lists are displayed and removed
- tasks are synced (add/remove) 
- at app launch, shows list fully populated at application start
- widget populates and stays populated even if app is closed

In both cases, their are two additional permissions which ARE enabled, `read tasks` and `write tasks`

I'll try and get my dev environment up next week so I might be able to provide more than just operational observation and speculation.

**Comment by dmfs** [comment]
That's probably because when you create the widget it stores the ids of the task lists you selected. When the lists are recreated by the sync app (because the provider deleted them as orphans), they get new, different ids. Hence the widget ignores the recreated lists.

**Comment by nickvergessen** [comment]
Works fine with the permissions granted, thanks!

**Comment by dmfs** [comment]
Version 1.1.10 now shows a permission request if the required `GET_ACCOUNTS` permission has not been granted yet. This will fix the problem.
