### ISSUE TITLE
item disappears, if cursor in it when tapping Edit

### ISSUE THREAD

**Issue by katrinleinweber** [dmfs/opentasks#419]
maybe related to #185 
 
In [v1.1.9](https://github.com/dmfs/opentasks/releases/tag/1.1.9) on LineageOS 14.1, OpenTasks displays the following data-losing behavior. To reproduce:

1. open a tasks
2. type in a sub-tasks / item
3. leave the cursor in that item's line
4. tap the pen / edit button => the "Check List" will have an additional line, but it's empty
5. save the tasks and check the Item list again => added item is gone

Please consider saving the newly added item somehow, when entering Edit mode even if one has not tapped the Enter key on the smartphone keyword to explicitely "finish" adding the item.

**Comment by dmfs** [comment]
Right. The task should be saved before performing any other operation.
