### ISSUE TITLE
Version 1.1.9 on Google Play

### ISSUE THREAD

**Issue by BlueIce** [dmfs/opentasks#423]
The current version available via Google Play is 1.1.8.2. Would be nice to have access to newest release (1.1.9).

**Comment by MisterY** [comment]
Just installed from the Play Store and got 1.1.9

**Comment by DJCrashdummy** [comment]
duplicate of #456

**Comment by BlueIce** [comment]
Actually #456 is a duplicate of _this_ issue. :wink:

But since most of the action is happening there i'm closing this one.

**Comment by DJCrashdummy** [comment]
@BlueIce you are completely right, but you also got the intention of my shortened statement right... :wink:
