### ISSUE TITLE
opentask <> caldav compatibility

### ISSUE THREAD

**Issue by Ollo1** [dmfs/opentasks#426]
Using CalDAV-Sync 0.4.32 (paid version of the PlayStore) does not allow installation of opentask 1.1.9 due to incompatibility reasons and the same vice versa. Latest opentask is not available from PlayStore.

**Comment by MisterY** [comment]
I just installed from the Play Store and got 1.1.9.

**Comment by dmfs** [comment]
opentasks 1.1.10 has been submitted to Google Play and should be available shortly.
