### ISSUE TITLE
Tasks dissapear from list if no connection to server

### ISSUE THREAD

**Issue by jemail99** [dmfs/opentasks#433]
If the app cannot connect to the server the task list is emptied. The Task list should be cached locally on the device then updated when and if connection to the server indicates an update is necessary.

**Comment by smithfred** [comment]
Well shit, I just came here to report the same issue :)

I'm seeing the same with Tasks 1.1.9, syncing to a CalDAV server using DAVdroid 1.8.1-ose

Kind of kills the entire point of sync.

**Comment by rodolfo-github** [comment]
This is happening to me too, I'm running my nextcloud server and using davdroid.
Could this be related to https://github.com/dmfs/opentasks/issues/404?

**Comment by smithfred** [comment]
Probably my issue too, I have the "contacts" permission disabled as mentioned in #404.

**Comment by dmfs** [comment]
Version 1.1.10 now shows a permission request if the required `GET_ACCOUNTS` permission has not been granted yet. This will fix the problem.
