### ISSUE TITLE
[feature] Possibility of handling repeating tasks?

### ISSUE THREAD

**Issue by rexxmagnus** [dmfs/opentasks#434]
I see that Thunderbird has the option of having a task automatically repeat on a given period. Is there potential for this to be implemented, so that a task gets marked as incomplete when the repeat period starts?

**Comment by BlueIce** [comment]
Possible duplicate of #26, #233 and #367.

**Comment by dmfs** [comment]
Right. FTR, we're working on test utilities to be able to test handling of recurring tasks in the provider: #418, #422

**Comment by dmfs** [comment]
This is now tracked under #462
