### ISSUE TITLE
Task lists and tasks not cached across app restarts

### ISSUE THREAD

**Issue by reuterbal** [dmfs/opentasks#435]
Hi OpenTasks team,

when I open the 'Tasks' app, tasks and task lists are almost always gone. Waiting for a while or hitting 'Refresh' from the menu brings them back. However, this takes almost a minute until the calendar names are back and then it starts slowly to show one task after another. When airplane mode is active (i.e., no data connectivity to the CalDAV-Server), no tasks or calendar names show up.

This issue persists since I switched to a new phone with LineageOS. I've been using DAVdroid and OpenTasks before on Android 4.2 on an older phone without these problems.

### Steps to reproduce:
1. Manually close Tasks app (or do not use it for quite a while) - i.e., make sure it's not running in the background.
2. Open Tasks app -> No tasks and no calendar names are shown.
3. Hit 'Refresh' (or wait for a long while)
4. Calendar names come back
5. Wait some longer: tasks reappear

### Configuration:
- Motorola Moto G4 Plus
- Android version: 7.1.2
- LineageOS version: 14.1-20170918-NIGHTLY-athene
- OpenTasks version: 1.1.9 (installed via F-Droid)
- DAVdroid version: 1.8.1-gplay

The behaviour is the same on my wifes phone (Moto G 4G, LineageOS 14.1).

**Comment by michal-s** [comment]
Hi, I experience totally same behaviour on my phone Xiaomy Mi A1, Android 7.1.2, OpenTasks 1.1.9, DAVdroid 1.9-ose. Thanks

**Comment by sam-hobbs** [comment]
I have the same problem, on Fairphone Open Source OS (Android 6.0.1) and v1.1.9 via Fdroid.

It freaked me out because I spent about an hour inputting tasks, closed the app and reopened it 15mins later and it looked like I'd lost the data.

A partial solution would be to display a message saying something like "retrieving tasks from remote server" until remote content is loaded.

However, that still doesn't solve the issue of losing access to my to do lists when no internet access is available, so some kind of cache would be ideal.

**Comment by reuterbal** [comment]
The issue seems to be related to missing permissions - or at least OpenTasks lack of asking for them.
The following fixed the issue for me:

1. Open the app permissions (Settings -> Apps -> OpenTasks -> Permissions)
2. Grant all permissions (Contacts, Additional permissions->read/write tasks)

Task lists have remained since then.

@Developers: Is it possible that the issue is related to missing permissions. Would it be possible to include some check at startup, that verifies that required permissions are granted, and if not, asks for them (similar behavior to, e.g., DAVdroid or other apps).

**Comment by sam-hobbs** [comment]
I can confirm that worked for me! Thanks @reuterbal!

Before I manually changed them, all three of those permissions were off.

**Comment by dmfs** [comment]
Version 1.1.10 now shows a permission request if the required `GET_ACCOUNTS` permission has not been granted yet. This will fix the problem.
