### ISSUE TITLE
Update relations when modifying `PARENT_ID` of a task.

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#454]

**Comment by lemonboston** [comment]
I suppose it make sense to do the existing relation clearing as part of this, right?

Having 2 internal operations:

- create relation:
  - add PARENT_ID to subtask in TASKS
  - remove all PARENT Relation Property from PROPERTIES for the subtask
  - add PARENT Relation Property

- remove relation:
  - remove PARENT_ID from subtask in TASKS
  - remove all PARENT Relation Property from PROPERTIES for the subtask

Does this sound good?
I suppose we can use OpenTaskPal for these 'internal' operations as well, right?
The question is how to make sure they are not used in the app.

**Comment by dmfs** [comment]
I'm leaning towards keeping the current behavior, having `PARENT_ID` read-only. So instead of this we should make sure you can't write to `PARENT_ID`

**Comment by dmfs** [comment]
Done.
