### ISSUE TITLE
Inexact alarms scheduled by AlarmManager.set()

### ISSUE THREAD

**Issue by frankFic** [dmfs/opentasks#468]
By the way, I also found `AlarmManager.set` is used to schedule a timeout in [NotificationActionUtils](https://github.com/dmfs/opentasks/blob/6d5db7bc045e4a74cedbea4461719637714a4897/opentasks/src/main/java/org/dmfs/tasks/notification/NotificationActionUtils.java#L326). For your reference, the behaviour of this API is changed since API 19, afterwards, the alarms scheduled by this API will be treated as inexact. ([doc](https://developer.android.com/reference/android/app/AlarmManager.html#set(int,%20long,%20android.app.PendingIntent))). After API 19, setExact will schedule the alarm at the exact time.

**Comment by dmfs** [comment]
Fixed in 1.1.10
