### ISSUE TITLE
caption of cancel button has line wrap

### ISSUE THREAD

**Issue by voxspox** [dmfs/opentasks#501]
The caption of the cancel button in the synchronized lists view wraps to "cance" / "l". This happens for a S4 mini with LineageOS 14.1 (Android 7.1.2)

**Comment by dmfs** [comment]
Note, this view is going to be removed. We'll change how and where the visible task lists are selected.

Anyway, can you attach a screen shot?

**Comment by voxspox** [comment]
![screenshot_20171124-001045](https://user-images.githubusercontent.com/1503565/33190466-530e097e-d0ad-11e7-8fef-57d9a05c0d80.png)

**Comment by dmfs** [comment]
Shouldn't be hard to fix that.
