### ISSUE TITLE
When Adding Items to Existing Checklist, Typing "Space" Key Moves the Insertion Point Backwards

### ISSUE THREAD

**Issue by alraban** [dmfs/opentasks#506]
This behavior only began occurring after the most recent update to Opentasks earlier today, earlier versions worked fine.

When I add an item to an existing checklist by pressing the "+ Add Item" button, text entry in the new box works as normal until I enter the first space character.  On pressing "space" after entering several characters the insertion point immediately returns to the beginning of the entry, after which spaces work as normal.  So for example, if I type "Chicken Noodle Soup" the field would have "Noodle SoupChicken" in it when I'm done.  The insertion point can be manually moved after it resets to work around the issue, but it makes it hard to enter any items with spaces, especially when working fast.  

I can reproduce this on two different phones. Of note this does not appear to happen when making a new checklist, only when editing an existing one to add items.

**Comment by dmfs** [comment]
I can reproduce this on my device. Not sure what has broken this. I think it's time to implement #323 and rewrite the entire checklist code.

**Comment by master-kenobi** [comment]
I'm facing this too

**Comment by lemonboston** [comment]
This change caused it: https://github.com/dmfs/opentasks/commit/174d0424258b2895c7e712ad63b208743d9afd82 , which was a fix for https://github.com/dmfs/opentasks/issues/419

I will work on this.
