### ISSUE TITLE
List selection text color too dark

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#526]
Since one of the recent commits, the list selection text color is black rather than white, see this image:
![screenshot_1512056073](https://user-images.githubusercontent.com/1614987/33438949-840feb5c-d5ec-11e7-9ac4-9cf9a8d534e2.png)

**Comment by lemonboston** [comment]
Strange, it is white for me:
![device-2017-12-04-205108](https://user-images.githubusercontent.com/1077972/33573017-ec928ac2-d934-11e7-93af-7dcb4db6b056.png)

Any tip how to reproduce it?
I've also looked into the code and I don't see any dynamic color setting in `TasksListCursorSpinnerAdapter` for the selected item `TextView`s.

And the style seems to be simply this:
```
    <style name="TextAppearance.Medium">
        <item name="textSize">18sp</item>
    </style>
```

**Comment by dmfs** [comment]
Which API version did you try?

**Comment by lemonboston** [comment]
It's Android 6.0.1 (API level 23) on a Nexus 5.

**Comment by dmfs** [comment]
Try the Android 7.1 emulator image.

**Comment by lemonboston** [comment]
Ok, I can see this on 7.0.
