### ISSUE TITLE
[Feature Request] share-button / share-function

### ISSUE THREAD

**Issue by new-on-github** [dmfs/opentasks#529]
A share button would be nice. At the moment I don't really care about the format, a text-format would be ok. A better and more practically format would also be nice.

**Comment by dmfs** [comment]
We've just recently released sharing for individual tasks (#172, released in version 1.1.10). Is that what you mean?

**Comment by new-on-github** [comment]
Oh, this sounds very good. I wasn't searching the iusse-list for "sharing" only for "share" (now it seems obvious...).

I am on version 1.1.9 (because this seems to be the newest version on F-Droid) therefore I have to wait to check the new feature. But indeed it seems to be the all I want.

Thanks a lot!

**Comment by dmfs** [comment]
Great! I'll close this. Please open a new issue if something is missing in 1.1.10.
