### ISSUE TITLE
Searching tasks finds non-matches

### ISSUE THREAD

**Issue by hg2581** [dmfs/opentasks#552]
How are searches done? Is it a combination of exact and fuzzy matching of the search term or is there possibly a bug in the search algorithm since non-matching tasks are also found?

**Comment by dmfs** [comment]
Searching is entirely fuzzy. We use a combination of 3-grams and 4-grams to get weighted search results. The more or longer search terms you enter the more precise the results should be.

We went for this fuzzy approach to be more tolerant about typos and different forms of a word.

Initially we were planning to give the 3-grams and 4-grams a weight based on their number of occurrences (n-grams which are rare would get a higher weight if they match) but we didn't see any need so far. Also that would increase implementation complexity and runtime overhead significantly.

If you get too many false positives we certainly should get back to that.

**Comment by hg2581** [comment]
How about first listing exact matches, then fuzzy matches?

**Comment by dmfs** [comment]
That's certainly possible. We would have to pre-process the results in that case because we could not express this with a single SQL query like we do now.
Maybe we can also improve the fuzzy search ranking like by taking consecutive n-gram matches into account.

**Comment by hg2581** [comment]
I think I would prefer exact matches at the top of the list, then fuzzy matches, the assumption being that I likely know what I am searching for and don't want the exact hits drowned by fuzzy matches (I have ca 30 calendars and over 1100 items in my task lists.)

**Comment by dmfs** [comment]
I've just made a few improvements in #556. The most important change is that it favours 4-gram matches over 3-grams matching multiple times. So it should give exact matches a higher score than multiple partial matches.

**Comment by hg2581** [comment]
Great, looking forward to testing it.

**Comment by dmfs** [comment]
@hg2581 this will be released this week in 1.1.13. Please let us know if you still see a need for further improvement with this version. Some concrete text examples would be helpful in that case.

**Comment by hg2581** [comment]
It seems to work well, I'll get back if I find any problems. Thank you!

**Comment by dmfs** [comment]
Thanks for the feedback. Good to hear it works better now.
