### ISSUE TITLE
Widget issues in Android 6.0

### ISSUE THREAD

**Issue by prppedro** [dmfs/opentasks#553]
Good afternoon, 
I'm using OpenTasks with your CalDav-sync thing. However, I've been trying with DAVDroid as well. Everything is fine inside the app (yellowish calendar is synced by DAVDroid, whilst pale green one is synced by DMFS CalDav). But the widget shows no tasks at all. 
![screenshot_20171206-104739](https://user-images.githubusercontent.com/9347060/33662741-257b56c6-da74-11e7-80c2-0ee4fbbe86c1.png)
![screenshot_20171206-104826](https://user-images.githubusercontent.com/9347060/33662743-259a14d0-da74-11e7-8112-15ef93547c07.png)
![screenshot_20171206-105211](https://user-images.githubusercontent.com/9347060/33662746-25fbf9ca-da74-11e7-9f80-304e90c1674c.png)
![screenshot_20171206-105223](https://user-images.githubusercontent.com/9347060/33662745-25dbb7fa-da74-11e7-861c-db962edd443f.png)
![screenshot_20171206-105258](https://user-images.githubusercontent.com/9347060/33662744-25be53fe-da74-11e7-9b14-2dcd4ca142d4.png)

It seems, however, to work with local lists. 
![screenshot_20171206-105526](https://user-images.githubusercontent.com/9347060/33662747-261b0e78-da74-11e7-9722-16d780d766ff.png)
![screenshot_20171206-105548](https://user-images.githubusercontent.com/9347060/33662748-26374e4e-da74-11e7-95da-8ecc963e5974.png)
![screenshot_20171206-105557](https://user-images.githubusercontent.com/9347060/33662749-2653e860-da74-11e7-8758-de6e454bf0d6.png)

Software info as follows: 
![screenshot_20171206-110006](https://user-images.githubusercontent.com/9347060/33662891-c3042af8-da74-11e7-995f-486e37034835.png)
![screenshot_20171206-105937](https://user-images.githubusercontent.com/9347060/33662892-c3245558-da74-11e7-994f-f3093a672194.png)

**Comment by dmfs** [comment]
Do your tasks have a start date?

**Comment by prppedro** [comment]
Yep. Just noticed it caused the issue. 
Hahahaha... Sorry about that.
