### ISSUE TITLE
Android Instrumentation tests to run with non-UTC default time zone

### ISSUE THREAD

**Issue by lemonboston** [dmfs/opentasks#571]
...in order to detect errors that may be caused by incorrect time zone handling.
---

Options:
1. Configure time zone in test (not sure if it is possible)
2. Configure time zone of test emulator (not sure if it is possible)

If none is possible, we could try to make sure to always use non-UTC `DateTime`s in tests, but that's not ideal.

**Comment by dmfs** [comment]
is this a duplicate of #570?

**Comment by lemonboston** [comment]
Yep
