### ISSUE TITLE
Update Chinese(Simplified) translation

### ISSUE THREAD

**Issue by vellxn** [dmfs/opentasks#583]
#558 
Sorry for the missing translations.

Last time editing with the Translations Editor of Android Studio, 
I didn't realize that the plural item wasn't generated and the comment style provided by string.xml(template) was removed. >_< 

I have write a patch for the missing translations, taking back the comments to match the template, 
and also some translation changes for improving accuracy.

Since the origin pull request was closed,
should I attach the new string.xml(values-zh-rCN) here directly, or do a merge and create a new pull request?

**Comment by dmfs** [comment]
Ideally you pull our current master (although this should be optional) and just open another pull request to update the strings file.
