### ISSUE TITLE
Color-Picker doesn't work on Android 8

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#590]
When opening the Color Picker on Android 8 a message is shown that "No apps can perform this action".
Apparently this is because the color picker activity has `exported="false"`. Overriding this with  `exported="true"` fixes this, but causes the Color Picker to be opened twice :-|

The goal was to allow using 3rd party color pickers which support the `org.openintents.action.PICK_COLOR` intent, while not exporting our own color picker at the same time. Apparently that doesn't work as intended.

If we can't solve this as intended we have two options:

* don't export the color picker and call it with an explicit intent
* export the color picker but make sure it doesn't open twice

**Comment by dmfs** [comment]
@lemonboston please look into this

**Comment by dmfs** [comment]
I'm not sure if 3rd party color pickers are really common. We probably should just keep the color picker private and open it with an explicit intent.

**Comment by dmfs** [comment]
Also see https://github.com/dmfs/color-picker/issues/8

**Comment by lemonboston** [comment]
I can't reproduce this on Android 8.0 emulator, for me the color picker works fine (with current master version). Any suggestion how I could reproduce this?

**Comment by dmfs** [comment]
It only seems to happen when another app which uses the same color picker is installed.

**Comment by mithodin** [comment]
I have the same problem in CalDAVSync on Android 7.1.2. I try to change a calendar's color, get the message "No apps can perform this action".

**Comment by cpw** [comment]
I have this on CalDavSync on Android 8 (v 4.3.2). It's very frustrating, as I have 6 different calendars (don't ask) and they're all stuck as RED (default colour?) Please release a fix?

**Comment by NiessenJuergen** [comment]
I migrated from Nexus 4 to Nexus 5x with Helium and also have to problem in CalDavSync:: "Diese Aktion kann von keiner App ausgeführt werden". Android 8.1.0, Sicherheitsupdates 5. Sept. 2018
