### ISSUE TITLE
Adaptive Icons for Android 8

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#593]

**Comment by lemonboston** [comment]
Just a note that Android Studio can help generate the new adaptive icons (File / New / Image Asset).

**Comment by c-e-p-x-u-o** [comment]
Please add support for icon shape
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

**Comment by c-e-p-x-u-o** [comment]
you should fix it to upload new version to google play
https://www.xda-developers.com/google-play-app-updates-must-target-android-8-0/

**Comment by dmfs** [comment]
Today I've started to roll out the new version (with adaptive icons). Unfortunately I had to stop it because someone reported an issue. I'll check that and release a hotfix if necessary.

**Comment by dmfs** [comment]
Closing this since it has finally been implemented.
