### ISSUE TITLE
Instance distance from current

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#606]
In #600 we've added an instance status column which allows to distinguish between closed, current and future instances. However, it just occurred to me that we can extend the semantics of this a bit and use the field as a kind of instance number (or distance) with `0` being the "current instance", `1` the next one, `2` the one after the next one, etc. So instance numbers `>0` would still denote upcoming instances but with the additional meaning of the distance from the current one. This could be useful in the UI. Since this is much less useful but much harder for closed instances, I propose to keep a "distance" of `-1` for all closed instances.

**Comment by dmfs** [comment]
Since the `instance_status` column would be superseded by `instance_distance` I'll reset the master branch to the 125f3e593d2879f2021d89358aaeb9623a374667 after branching from d0ff43eeeb592a98392f39cec2fee0002ed690f3 into `stories/606-instance-distance`, hoping no one has pulled he new master yet.

**Comment by lemonboston** [comment]
I see that this instance number can increases the utility of this field.

What is not clear for me is what is the distinction between the current one `0` and next one `1` for recurrent tasks?
So let's say I have a weekly recurrent task on Wednesday and it's Monday now, what number would the task on Wednesday have?

**Comment by dmfs** [comment]
If there is no other instance between now and Wednesday, the one on this Wednesday would be `0` and each instance thereafter would have it's number increased by `1` (compared to its predecessor).
