### ISSUE TITLE
Small tablet details view doesn't have FAB

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#614]
The portrait details view on a small tablet doesn't have a FAB but shows the complete button in the toolbar.

**Comment by lemonboston** [comment]
There is a bool resource for this which is set to `false` for sw600dp. So above 600dp minimal width the FAB is never shown. @dmfs Do you remember why is that? Should we remove that flag and always show the FAB?

**Comment by dmfs** [comment]
ah, I guess we did that to be consistent with landscape mode. Landscape mode on small tablets has a FAB, but it's the "add task" button and the "complete task" option is in the details toolbar. So in order to be consistent we kept the complete option on the toolbar in portrait mode. However, I think we should show a FAB in that case now.

**Comment by lemonboston** [comment]
Does this change mean we can just use the `has_two_panes` flag instead? So show complete task FAB in single pane, not show in two-pane mode, right?

**Comment by dmfs** [comment]
right.

**Comment by dmfs** [comment]
fixed
