### ISSUE TITLE
Bug in two-pane mode: Tab bar icons disappear after task added with editor

### ISSUE THREAD

**Issue by lemonboston** [dmfs/opentasks#643]
Steps:
-- clean install on a tablet in landscape mode 
-- tap the FAB to create a new task
-- add title, click save
Actual: on the restored list view (left pane), the tab bar icons are not shown
Expected: they are shown

![device-2018-01-19-153730](https://user-images.githubusercontent.com/1077972/35155672-b3028852-fd2e-11e7-9826-2dfe9903a4b5.png)

---

I know we've encountered this before but I couldn't find a ticket for it.

**Comment by dmfs** [comment]
There was no ticket. It was in the comments of a PR.

**Comment by lemonboston** [comment]
I am closing this since the related pull request has been merged.
