### ISSUE TITLE
Editor title changed to "new task" after rotating

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#658]

**Comment by lemonboston** [comment]
@dmfs Was it a one-off or can you reproduce it? I can't, so steps, app and android version could help. I also don't any see 'new task' string resource or literal string in code , so I am not sure how that could show up.

**Comment by dmfs** [comment]
I was able to reproduce it on the first attempt. When you open an existing task in the editor and rotate the device, the activity title changes from "edit" to "create".

**Comment by lemonboston** [comment]
Ok, I can reproduce that. (My eye was looking for 'new task' as per the bug title, and also mostly trying the editor for new task and not editing existing one.)
