### ISSUE TITLE
Warning before automatic image upload

### ISSUE THREAD

**Issue by holzdroid** [dmfs/opentasks#662]
I wanted to generate a task from a related photo. After "sharing" the image with opentasks, it asked me whether I want to link an album or create some kind of link. I choose link - without knowing that this app would actually upload my image to Google.
I found no related choice in the settings and I have no idea how to remove this image from where it has been uploaded to. Please fix this - not everyone considers Google a friend..

**Comment by dmfs** [comment]
I think you're mixing something up. OpenTasks doesn't support photos yet nor does it upload anything to anywhere. It doesn't even have "Internet" permissions.

**Comment by holzdroid** [comment]
Yes you are right. There's no way to attach images to tasks, so Android knows that it may only share text with the OpenTasks.
Thus, another app "share link" is started, which is responsible for the undesired behavior described above. I could reproduce the problem sharing an image with the barcode scanner app, which also doesn't understand image files. Unfortunately, I can't find the app to uninstall it, but it's set as the first choice for sharing: https://photos.app.goo.gl/2dGB4iiibims8x6w1

**Comment by holzdroid** [comment]
The app is called Google Photos. This article (at the bottom of the page) explains how to stop sharing (as I did with the above link): https://support.google.com/photos/answer/6131416
