### ISSUE TITLE
CardDAV not always synching?

### ISSUE THREAD

**Issue by hg2581** [dmfs/opentasks#663]
I have several phones and a tablet, and computers (Thunderbird) syncing their addressbooks against an owncloud backend. I have discovered that the phones not always, or it takes several days, to sync updated addressbook information. The phones and tablet settings for CardDAV is set to sync every four hours in both directions.
Is there possibly a bug in addressbook syncing? I have confirmed that both owncloud and Thunderbird contain the correct, updated addressbook information so it seems the problem is on the Android side.

**Comment by linkp** [comment]
Nothing you referenced would have anything to do with this app. OpenTasks access tasks stored in CalDAV backends and has nothing to do with address book sync over CardDAV.

**Comment by hg2581** [comment]
Sorry, missed that support for CardDAV is via the e-mail address.

**Comment by dilyanpalauzov** [comment]
Time to close the ticket?

**Comment by hg2581** [comment]
On October 13, 2018 6:15:51 PM EDT, "Дилян Палаузов" <notifications@github.com> wrote:
>Time to close the ticket?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dmfs/opentasks/issues/663#issuecomment-429579717

Yes
