### ISSUE TITLE
Bug found while setting Pulse light notification on Tasks app

### ISSUE THREAD

**Issue by darewealth** [dmfs/opentasks#670]
#### Expected behavior
When setting Pulse light notification on tasks app my phone light should be on to notified me .

#### Actual behavior
When I set Pulse light notification it only display the notification but didn’t on the screen light  

#### How to reproduce
(1) Download[ Tasks ](https://play.google.com/store/apps/details?id=org.dmfs.tasks)app launch it and open

(2)  Set notification to Pulse light and set tasks  

Device used: Gionee P5 mini

Operating system: Android version 5.1

*App version: 1.1.13

#### Recording Of The Bug
https://youtu.be/_6mrOd5xDik
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@darewealth/bug-found-while-setting-pulse-light-notification-on-tasks-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by lemonboston** [comment]
The light has to be enabled in the phone settings too as mentioned on utopian already:
[link](https://utopian.io/utopian-io/@darewealth/bug-found-while-setting-pulse-light-notification-on-tasks-app#@thewizard.studio/re-darewealth-bug-found-while-setting-pulse-light-notification-on-tasks-app-20180328t023311257z) (contribution is not approved as a consequence)

I think we certainly don't want to override the phone settings by the app, hence closing this.
