### ISSUE TITLE
Terminating dot in the permissions' spelling 

### ISSUE THREAD

**Issue by dilyanpalauzov** [dmfs/opentasks#688]
When DavDroid is installed, it asks for permissions to share information with OpenTasks with 
`Allow DavDroid to Create, modify and delete tasks and task lists.?`  Notice the weird fullstop before the question mark.  This could help:
```diff
diff --git a/opentasks-provider/src/main/res/values/strings.xml b/opentasks-provider/src/main/res/values/strings.xml
--- a/opentasks-provider/src/main/res/values/strings.xml
+++ b/opentasks-provider/src/main/res/values/strings.xml
@@ -7,8 +7,8 @@
     <!-- Permissions -->
 
     <string name="opentasks_permission_read_tasks">read tasks</string>
-    <string name="opentasks_permission_description_read_tasks">Read tasks and task lists.</string>
+    <string name="opentasks_permission_description_read_tasks">Read tasks and task lists</string>
     <string name="opentasks_permission_write_tasks">write tasks</string>
-    <string name="opentasks_permission_description_write_tasks">Create, modify and delete tasks and task lists.</string>
+    <string name="opentasks_permission_description_write_tasks">Create, modify and delete tasks and task lists</string>
 
 </resources>
```

**Comment by dmfs** [comment]
Right. On older Android version there was no Question, because permissions were granted automatically at runtime, hence the full stop.
I guess is would also make sense to start with a lower case letter.
Would you care opening a pull request?

**Comment by dmfs** [comment]
I disagree, I'd create a PR even for a single bit. It's not really a lot of overhead IMO. In the end it's probably comparable to what you did to open this ticket.
Anyway, I can also do it myself of course.

**Comment by dilyanpalauzov** [comment]
Please take care of this.

**Comment by dmfs** [comment]
I've made this change in the course of #704. I had to add new descriptions and removing the dots in this commit felt like a good idea.
