### ISSUE TITLE
Desktop accessibility of opentasks?

### ISSUE THREAD

**Issue by akke-t** [dmfs/opentasks#691]
Hi, I am not sure if this is the right place to ask this question since it is not a bug, so after looking at:

- https://gist.github.com/ccannon94/4980dc78456cb7a7ab38028e933cb01e
- https://webapps.stackexchange.com/questions/53170/how-to-ask-questions-on-github

I figured I will ask it here, please let me know if I should ask this somewhere else. 

**Is there a way to open, view and edit open tasks on a desktop?** (Without running an android emulator with open tasks in it.) 

Currently I am trying the following two options, but I have not yet been successful in it:

- Using davdroid to sync your tasks from a server, with google tasks being the server.
- Synchronizing the task lists from VueMinder to gmail to android Opentasks.

Any other suggestions are welcome!

**Comment by fhunter** [comment]
Opentasks with davdroid supports any caldav server for sync. So you just sync desktop app with the same server that was used on android.
For console - there is pair of vdirsyncer + todoman. For gui - evolution/rainlendar2/thunderbird/any other desktop app supporting vcalendar should work.

Just a warning - last time I checked (few years ago) - Google does not provide VTODO support on calendar, so tasks have separate API. But that can be outdated information.

**Comment by akke-t** [comment]
Thank you for your complete response. I was unaware a desktop app exists for/with opentasks. Thank you for referring to the desktop apps for console and gui, which can be installed on windows and then synced with the caldav server (such as google, or your own) and then from that server to android via Davdroid!
