### ISSUE TITLE
Refresh/sync not working with Oreo

### ISSUE THREAD

**Issue by maulwuff** [dmfs/opentasks#694]
When I click "Aktualisieren" (Refresh/Sync?) in the app, nothing happens on Android 8.1.0
I open the caldav app afterwards and see something like "last sync: yesterday ..." instead of "one minute ago" or similar.

What is the intention of the "Aktualisieren" button? Is it the same as in calDav "Jetzt synchronisieren"?

**Comment by dmfs** [comment]
Yes, this button is supposed to sync all accounts with task support. Could this be a permission issue? Does the app have the permission to read all accounts on the device?

**Comment by maulwuff** [comment]
Thanks, that fixed it. Read and write permission for tasks was not granted, only read contacts. 

Am 8. August 2018 00:52:59 MESZ schrieb Marten Gajda <notifications@github.com>:
