### ISSUE TITLE
task is not showning in widget list, when a due date is set

### ISSUE THREAD

**Issue by Micha-Btz** [dmfs/opentasks#701]
Hi there,

at first, thanks for this nice app.

When you create a new task and you set a due date and time, the task is not showing in the widget list.
If you go to the app itself, the created task is showing, but not in the widget.

Android 8.1, Patchlevel Juli, BQ Aquaris Stock Rom 1.3.

Would be great it can be fixed.

TIA Micha

**Comment by dmfs** [comment]
Did you also set a start date? At present the widget only shows tasks which have started already (i.e. have no start date or a start date in the past).

**Comment by Micha-Btz** [comment]
Tests today doen't show this behaviour. Seems that I can create a task with a due date without a start date.
