### ISSUE TITLE
Update target SDK to 26 or newer

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#703]
In order to comply with the latest Play Store requirements we need to support target SDK of at least 26. We need to check if that affects any background operations like due notifications.

**Comment by MisterY** [comment]
If it will help, as I went through the same exercise in [mmex4android](https://github.com/moneymanagerex/android-money-manager-ex), the same issues were handled, i.e. notifications and background jobs:

- https://github.com/moneymanagerex/android-money-manager-ex/issues/1190
- https://github.com/moneymanagerex/android-money-manager-ex/issues/1145

You can have a look at the code or search through the issues and look for "Android 8" or "Oreo".

**Comment by dmfs** [comment]
Thx. I think I'm almost done with it. We don't have that many background services. I just need to create resource strings for the notification channel names and update the notification settings to redirect to the new Activity provided by Android for that.

**Comment by dmfs** [comment]
I've just merged the PR. Hope it works for everyone.
