### ISSUE TITLE
Request account visibility

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#728]
Android 8 adds some limitations on account visibility for apps which target SDK level 26+.
In particular an app no longer sees available accounts until it has been granted a certain "visibility" on that account.
As a result, OpenTasks now removes task lists, even though the account they belong to still exists.

Sync apps should call [setAccountVisibility](https://developer.android.com/reference/android/accounts/AccountManager#setAccountVisibility(android.accounts.Account,%20java.lang.String,%20int)) for every account they wish to sync to OpenTasks.

We need to decide whether OpenTasks should also ask the user for access to that account. The problem is that we'll have to do that for every account which no longer exists because we won't be able to distinguish between accounts "invisible" to OpenTasks and accounts that don't exist without tracking the accounts we have been granted access to.

**Comment by dmfs** [comment]
I consider this a blocker for the full roll-out on Google Play, because it would affect all DavDroid users.

**Comment by dmfs** [comment]
Looks like I've foreseen this issue in #596 :-|

**Comment by dmfs** [comment]
The only solution for OpenTasks seems to be to call [newChooseAccountIntent](https://developer.android.com/reference/android/accounts/AccountManager#newChooseAccountIntent(android.accounts.Account,%20java.util.List%3Candroid.accounts.Account%3E,%20java.lang.String[],%20java.lang.String,%20java.lang.String,%20java.lang.String[],%20android.os.Bundle)) if a list for an "invisible" account has been created.
On the plus side we can get rid of the "GET_ACCOUNTS" permission request because it's not longer being used.

**Comment by dmfs** [comment]
Here is what we can do:
1. Whenever a new list is created, we test if we can "see" the account it belongs to
2. If we can see the account we move on
3. If we can't see the account we post a notification which makes the user aware of the issue
4. When the notification is clicked the user is prompted to grant permission to "see" the account

In addition we can show an alert dialog in the UI.

Though, this approach alone will still cause existing lists to be purged after an upgrade to OpenTasks 1.1.14 or later.

**Comment by rfc2822** [comment]
[I have added account visibility in DAVx⁵ for SDK ≥ 26.](https://gitlab.com/bitfireAT/davx5-ose/commit/036fc405f404abf6258a24539ae9fdf8096ea949) Maybe this could be documented somewhere in the `TaskContract` so that client developers know they have to allow OpenTasks to see their accounts?

**Comment by dmfs** [comment]
Released in 1.1.16
