### ISSUE TITLE
Dav acounts disappeared from opentask

### ISSUE THREAD

**Issue by Mannshoch** [dmfs/opentasks#735]
I installed DAVx5 confugured my nextcloud and added opentask after that. The task appeared vor some minute. After I removed a caldav from synchronized calendar in "simple calendar", all dav calendars disappeared from opencalendar. 
Reverse it not worked.
I granted all rights and also tried to uninstall reinstall opentask.

**Comment by dmfs** [comment]
This should be fixed in the latest DAVx5 release as well as OpenTasks 1.1.16. Please reopen if this is still an issue with the latest releases.
