### ISSUE TITLE
Lag in usage

### ISSUE THREAD

**Issue by wurstmuffin** [dmfs/opentasks#738]
Using the Tasks app on my OnePlus 5T. Same behavior on Android 8.1 and 9.0 (OxygenOS 9.0.2).
Installed the app from F-Droid (1.1.15).

Sometimes while using the app it freezes. I have to wait, and from time to time, tap on it to see if it is back again. If I was writing a new entry within the task, the entry is discarded.

Installed it now from Google Play/Store, v. 1.1.16, will see if the same behavior happens

**Comment by dmfs** [comment]
Under which conditions does that happen? Only when you edit tasks or can that happen at any time? Can you see a pattern?
Do you see any ANR message?
I'll check the ANR reports on Google Play.

**Comment by MaDill** [comment]
It's kind of random. I have it most of the time with some todo lists with checkboxes. Sometimes during creating it and sometimes when I just set the checkmarks. I use it often for shopping lists and then I notice it. The shopping list is mostly longer with around 20 items. I press then the home button (middle), then the recent apps button (right) and swipe the app to the right to close it. When I open it again it is working well again.
Is an ANR message means app not responding? If yes, then I not receive it.

**Comment by dmfs** [comment]
Did the issue start with the latest release or did you see it in 1.1.13 before?
Currently, I have two suspects. The notification handler and full text search. Though I'd expect both of them to affect primarily save (or sync) operations.
I'll add a few profiling logs hoping they reveal the culprit.

**Comment by MaDill** [comment]
I have this since a longer time. Sorry I can not answer your question with the version number.

**Comment by dmfs** [comment]
The upcoming release has some major improvements in its full text search indexer. Inserting and updating tasks is now a lot faster. If a sync adapter was updating tasks in the background it could have affected performance and potentially caused such a lag.
I'll release 1.1.17 today, please let me know if the issue still exists with the new version. I'll also add a few profiling logs to the task provider. But you need to be able to read the logcat in order to see them.

**Comment by dmfs** [comment]
Please let me know if you still see the issue in the latest release. Building the full text search index is a lot faster now.

**Comment by wurstmuffin** [comment]
Hey. I had a short lag after modifying a task. I pressed the back button if 
the Android nav bar and it took a while until the app reacted.

**Comment by dmfs** [comment]
I'm going to refactor the notification service now. This is another candidate which could well be the reason for this. The current implementation appears to be far from ideal and might cause more database I/O than necessary.

**Comment by MaDill** [comment]
Since a few days I have the update to 1.1.17 installed. It feels a bit smoother, but stuck still from time to time. Especially when the notifications are running through for around 10 to 20 seconds.

**Comment by dmfs** [comment]
I've just started the staged roll-out of 1.1.18 which contains a number of changes regarding notifications. Please let me know if this is still an issue with 1.1.18.

**Comment by dmfs** [comment]
I'll close this one now. Please file a new issue if a notable lag still exists in 1.1.18.
