### ISSUE TITLE
I can't open it on android 9 with EMUI 9

### ISSUE THREAD

**Issue by leschek** [dmfs/opentasks#742]
I can't open it (version 1.1.16-2-g5d6d35ca) on android 9 with EMUI 9 (Huawei mate 20 pro).

**Comment by dmfs** [comment]
that's the beta version, have you tried the regular one?

**Comment by dmfs** [comment]
Did you install the app as an upgrade from a previous version? Maybe the migration is going wrong. I'll check that.

**Comment by dmfs** [comment]
I think I know what's going on. I'll post an update.

**Comment by dmfs** [comment]
I've uploaded a hotfix, please let me know if the issue still exists in `1.1.16-3-ga2567c4b`

**Comment by leschek** [comment]
I just updated to the new version and it seems it is working.

**Comment by dmfs** [comment]
Great!
