### ISSUE TITLE
Oreo long icon press shorcut

### ISSUE THREAD

**Issue by 532910** [dmfs/opentasks#771]
Please add support for icon press shortcut
https://developer.android.com/guide/topics/ui/shortcuts/

I'd like to see create new task action in the shortcut list.

**Comment by dmfs** [comment]
Duplicate of #715 
This is already planned. It shouldn't be difficult to implement this. The most pressing issues are notifications and testing/merging the recurrence branch though. However, I may be able to squeeze this in during the next couple of weeks.

**Comment by 532910** [comment]
Sorry.
