### ISSUE TITLE
Completed tasks spawn notifications after reboot

### ISSUE THREAD

**Issue by virhonestum** [dmfs/opentasks#800]
Every time I reboot my phone as soon as it has booted up again, I get a notification for a few tasks I have already completed. I think it is usually 4, and they aren't grouped into a notification group, but I need to swipe every notification away one by one.

![Screenshot](https://user-images.githubusercontent.com/26956711/59093687-d0fb6b80-8914-11e9-800f-9d743f54ba77.jpg)

I'm on app version 1.1.18

**Comment by justdave** [comment]
I get this, too, and more than 4. Immediately after the update from the other day installed I got about 10 of them.

**Comment by dmfs** [comment]
Looks like the persisted notification state is not cleared when you swipe the notification away. Shouldn't be hard to fix. I'll have a look.

**Comment by virhonestum** [comment]
Hey,

When will a new release which includes this bug-fix be published on F-Droid?

Thanks

**Comment by dmfs** [comment]
@virhonestum that depends on when F-Droid picks the new version up, see #550. I've just published a new version. Hopefully F-Droid is able to build it.
