### ISSUE TITLE
Categories are removed when edited via App.

### ISSUE THREAD

**Issue by googol42** [dmfs/opentasks#839]
Hello,

I am aware of #14 (Feature Request: Sync Categories). Though it would be cool, if categories would be synced, but that is not the matter of this report.

When I add categories (e. g. on Nextcloud) and I edit the task via the app, the categories are removed.

## How to reproduce
1. Create Task with Category
1. Wait for Task being synced to phone
1. Edit task on phone
1. Wait for Task being synced to Nextcloud

## Result
Category was removed from task

## Expected
Category should not be removed from task

**Comment by dmfs** [comment]
Categories are not removed by OpenTasks, but by your sync app. OpenTask doesn't have much code for categories yet. The database tables for categories exist and in theory they should be ready to be used but it's still untested code. Though, if a category is inserted by a sync app, it remains there, untouched by OpenTasks.

**Comment by googol42** [comment]
Alright, I thought it would be OpenTasks which removes the category, because as long as I don't edit the task, the category stays there. I use DAVx⁵ for syncing.

**Comment by googol42** [comment]
I reported this upstream and they have a fix.
