### ISSUE TITLE
Checkbox for done in Overview

### ISSUE THREAD

**Issue by jakobroehrl** [dmfs/opentasks#852]
Hi @dmfs!
Thanks for the great app!
It would be nice to have a done/undone checkbox direct in the Tasks Overwiew. 
I use Taks as Shoppinglist and it's a litte bit hard to tip for every piece I lay in the shopping basket on the Task, Edit, Status > done, Save

Thanks!

**Comment by dmfs** [comment]
@jakobroehrl in the task list you can tap and hold a task and then fling it to the right to complete it (or fling a completed task to the left to resume it). I'm planning changes to get rid of the "hold" part but for now this should do the trick.
Also, you don't have to open the editor to complete a task. You can just tap the check mark button in the details view.
If you're referring to the widget, I'm planning to add something to complete a task more easily.

**Comment by jakobroehrl** [comment]
Thank you, I did't see the function. 
It's working :)
