### ISSUE TITLE
The +1 day action doesn't work from the notification area

### ISSUE THREAD

**Issue by mdimjasevic** [dmfs/opentasks#865]
When I expand the notification area on my phone and there is a task that I haven't done that is due today, I'd like to make it due tomorrow by pressing the "+1 day" action. However, this doesn't work and it has no effect on the task. On the other hand, when I open the task in the application, pressing "+1 day" gives the expected result by extending the due date by one day.

Please fix this by making the "+1 day" action in the notification area extend the due date by one day.

Application source of installation: F-Droid
Application version: 1.2.2
OS: Lineage 16.0 (Android 9)

**Comment by rainerzufall** [comment]
I can confirm this behaviour:
Application source of installation: Google PlayStore
Application version: 1.2.2
OS: Android 9

**Comment by dmfs** [comment]
This has already been fixed with #858 and will be released in 1.2.3 by the end of the week.

**Comment by dmfs** [comment]
1.2.3 has just been released and it should fix this.
