### ISSUE TITLE
+1 day doesn't work in notifications for 1.2.2

### ISSUE THREAD

**Issue by wired2051** [dmfs/opentasks#869]
I use OpenTask since 2017 with Android 7.0 (Huawei P9 lite, EMUI 5.0.4) and DAVx5 2.5.5-ose, installed with F-Droid.

After Update to OpenTask 1.2.2 there are no buttons on the lock-screen anymore and after unlock and pulling down the notifications from top of the screen, there is a _done_ and a _+1 day_ button but only the _done_ button works fine (that's a pity). In the OpenTask GUI the _+1 day_ and the _+1 hour_ button work as expected - it's only the notifications.

Till OpenTask 1.1.20 I used _+1 day_ also on the lock-screen - very convenient. 

I tried to downgrade to 1.1.20 and 1.1.19 with F-Droid but both failed "for unknown reason".

**Steps to reproduce**:

1. Create a new task
2. set due
3. Save task
4. wait
5. pull down notification from top of the screen and try _+1 day_

**Comment by dmfs** [comment]
This has already been fixed in 1.2.3, see #865 and #858 
Downgrading doesn't work due to changes in the database schema.
