### ISSUE TITLE
Support markdown lists with dash for checklists

### ISSUE THREAD

**Issue by unclev** [dmfs/opentasks#875]
As _OpenTasks_ is often used with _Nextcloud_ there is an inconsistency in representing list (in Nextcloud description field), and _OpenTasks_' checklist.

For eg., the following list created in _Nextcloud_

```
- [x] Show the standard format usage (supported by Nextcloud): copy markdown
- [ ] How it is shown in the Android Tasks app: take image
```

renders pretty much the same as on GitHub

> - [x] Show the standard format usage (supported by Nextcloud): copy markdown
> - [ ] How it is shown in the Android Tasks app: take image

in _OpenTasks_ (v1.2.3 from _F-Droid_) goes into Description as plan text.

And vice versa, _OpenTasks_ checklist does not render to list in _Nextcloud_.

> [x] Show the standard format usage (supported by Nextcloud): copy markdown
>
> [ ] How it is shown in the Android Tasks app: take image

I have not seen a markdown flavour or renderer that treats `[ ]` and `[x]` as check list item, so it is probably worth treating `- [ ]` and `- [x]` as checklist items as well. (`[ ]` and `[x]` for backward compatibility).

For new list items on an existing list I suggest _OpenTasks_ to remember the last synchronization result, and to follow the convention used in the source.

This request is likely competes with #323, and a kind of checklist format extension similar to #265.

**Comment by dmfs** [comment]
Makes sense to me. I don't see a need for retaining the conventions used for a specific source. This would only make it more complicated for little benefit (if any at all).

**Comment by dmfs** [comment]
This should be fixed in the upcoming release.
