### ISSUE TITLE
[TODO] Relating task processor doesn't update parent_id

### ISSUE THREAD

**Issue by rfc2822** [dmfs/opentasks#877]
When a sync adapter manages relations by inserting `Relation` rows with `RELATED_UID`, it's possible that the related task is not synchronized yet, so `RELATED_ID` can't be set when the child task is inserted.

The Relating task processor handles this situation correctly and updates the children's `RELATED_ID` as soon as the parent is inserted. [However, it does not update the `parent_id` field of the child task row itself.](https://github.com/dmfs/opentasks/blob/598a6c72d80e4cff13de16e05852363d36afff33/opentasks-provider/src/main/java/org/dmfs/provider/tasks/processors/tasks/Relating.java#L38)

A sync adapter can touch (update without changes) all `Relation` rows after the sync is completed to trigger `parent_id` calculation. Is there a better solution at the moment?

Maybe the `parent_id` could be updated using an SQL trigger whenever a `Relation` is inserted/update/deleted? Then no redudant code would be required.

If you agree, I can try to create such a trigger and submit a PR.

**Comment by dmfs** [comment]
At present there is no better solution.
A trigger certainly would keep things simple. The only downside I see is that it also would cause "bogus updates" on `parent_id` when you update the `parent_id` (I mean once #454 has been implemented). In that case the Java code would create or update a relation and the trigger would write back the same `parent_id`. The overhead is certainly negligible, though.
