### ISSUE TITLE
All-day tasks and time zone

### ISSUE THREAD

**Issue by ghost** [dmfs/opentasks#90]
Is there a way to set time zones for "All Day" tasks? I'm in EST (GMT-4) time zone but tasks I create are being shown in UTC/GMT in some places.

e.g. If I create a task that's due on July 20 (which it correctly shows on the actual task's detail page), it says "Jul 19, 2014" on the Current Tasks widget. Also, on July 19 at 8:00 PM EST, I get a notification that the task is due.

**Comment by dmfs** [comment]
This has been fixed as a side-product of another issue in OpenTasks-Provider. All-day task notifications should show up at midnight in the current time zone now. While this is still far from being ideal (we plan to add an option to show all-day task notifications at a specific time on that day or the day before), it's at least a more deterministic behavior.
