### ISSUE TITLE
Ending Time of Completed Task is Different

### ISSUE THREAD

**Issue by Russe** [dmfs/opentasks#923]
I noticed that the time displayed from a completed task in overview mode is not the same like in edit mode.

OS: LineageOS 16
App-Version: 1.2.4 (F-Droid)

Example:
1. create new task
2. set beginning time to current time less some minutes (eg. 13:25)
3. set ending time to current time (eg. 13:30)
4. save task

Now in overview mode of this task the beginning time is the same, but the ending time is 14:30 instead of 13:30.
When editing the task again the ending time is correct with 13:30.

I guess this is something with the time zone, I'm in Germany (GMT +01:00)
Maybe this is the same bug as in https://github.com/dmfs/opentasks/issues/224 ?

**Comment by dmfs** [comment]
Which time zone does the task editor show when you create the task?
Which one does it show when you edit it the second time?

**Comment by Russe** [comment]
When creating the task the time zone is: (GMT+01:00) Brussels.
It's the same time zone when adding the second time (ending time).
But when saving the task the app jumps to the overview of this task, and there's not time zone displayed but the wrong time.

**Comment by dmfs** [comment]
Any chance you can record a screen cast of this? I'm having a hard time reproducing this issue.
Is the task synced correctly to your server or is the due date off by an hour too?

**Comment by Russe** [comment]
Sorry for the delay.
I did some further tests, now the difference are two hours (last night there was switch to summer time here in germany).

Here are the screenshots.
I did the tests and screenshots at 8 pm local time (germany).

Added a new task, set beginning time to  7 pm. 
![01-create-beginning-time-s](https://user-images.githubusercontent.com/1218375/77857103-e3c09300-71fb-11ea-805e-0bf57d22e653.png)

Saved the task, at summary beginning time is 7 pm.
![02-save-and-summary-s](https://user-images.githubusercontent.com/1218375/77857105-e4592980-71fb-11ea-94f2-e474e39ed902.png)

Went to edit mode and added the ending time 8 pm.
![03-add-ending-time-s](https://user-images.githubusercontent.com/1218375/77857106-e4592980-71fb-11ea-9590-52c2556e7a7a.png)

Saved the task, at summary the ending time is now 10 pm instead of 8 pm.
![04-save-and-summary-s](https://user-images.githubusercontent.com/1218375/77857107-e4f1c000-71fb-11ea-812d-07436963c42e.png)

When synced to the server there's also 10 pm ending time instead of 8 pm.
![05-server](https://user-images.githubusercontent.com/1218375/77857108-e4f1c000-71fb-11ea-9f11-5dafd395a368.png)

Hope this will help you.

**Comment by dmfs** [comment]
Thank you that helps a lot. I can actually reproduce it now. How some reason I was testing the due date instead of the completed date. o_O
Should be easy to fix.
