### ISSUE TITLE
Tasks don't sync correctly with Nextcloud

### ISSUE THREAD

**Issue by iteco** [dmfs/opentasks#926]
I am using Nextcloud Task app (https://github.com/nextcloud/tasks/) version 0.12.1 with nextclould 18, and latest Tasks app (version 1.2.4), and sub tasks in Nextcloud will be visible as normal tasks in Task app, and sub tasks in Tasks app will go to comments in the Nextcloud task app. See the same in the attache image.

![tasks_bug2](https://user-images.githubusercontent.com/4575046/77800237-05484000-707f-11ea-88da-6616d8f96a32.png)

**Comment by raimund-schluessler** [comment]
Duplicate of https://github.com/dmfs/opentasks/issues/37.

**Comment by fromage9747** [comment]
@iteco How do you even set up your nextcloud settings in the app? When I click on the vertical ellipses and press on settings I go to the Android App settings for the app to turn off notifications and badges.  It does not take me to any settings within the app itself.

**Comment by iteco** [comment]
> @iteco How do you even set up your nextcloud settings in the app? When I click on the vertical ellipses and press on settings I go to the Android App settings for the app to turn off notifications and badges. It does not take me to any settings within the app itself.

Under the settings are: notifications, sound, vibrate and Pulse light. All can be turned on or off. There is nothing more.

To get the app to sync with nextcloud you will need other app [davx5](https://f-droid.org/en/packages/at.bitfire.davdroid/).

**Comment by iteco** [comment]
I filed also a [help request](https://github.com/nextcloud/tasks/issues/936) to nextcloud guys as I thought that this was just a mistake that was not fixed in Tasks app because of more limited resources.

I got back references to other issues (I didn't find them in first place, although I tried to search them) telling that the case is more complex. Referred issues are below.  
https://github.com/nextcloud/tasks/issues/116
https://github.com/dmfs/opentasks/issues/37
https://github.com/nextcloud/tasks/issues/159

However, looking those, I see that subtasks have been on the plans years.. Perhaps nextcloud guys could give a hand on that ?

Anyway this is duplicate for the #37, so closing this.

**Comment by fromage9747** [comment]
@iteco like I said in my comment. When I click on settings it takes me to the Samsung system settings for the app and not the normal app settings that you have described. I have a Samsung Galaxy note8 with Android 9. everything is stock.

I will upload a video of it.

**Comment by fromage9747** [comment]
@iteco Here is a video of what I get when I click on settings:

https://www.dropbox.com/s/0utvnmtb1i7nonf/20200329_093926_Trim.mp4?dl=0
