### ISSUE TITLE
Crash on add task

### ISSUE THREAD

**Issue by splack** [dmfs/opentasks#93]
If you hide local tasks, don't have any other remote sources then add a task and hit plus the app crashes.

**Comment by lemonboston** [comment]
Is this still relevant? I checked that if no lists are selected to display and I add a task with the plus FAB on home screen, then the task editor screen comes up where my local list is already selected, so there is no problem in this case.

**Comment by dmfs** [comment]
@lemonboston try not just to hide the lists, but also to disable sync for all list. The issue occurred because the task editor only shows synced lists and it crashed when there is no synced list at all. We should catch the case that there are no writable & synced lists and show a notification in that case.

**Comment by lemonboston** [comment]
@dmfs Would it be an sufficient solution to check whether the `Cursor` for the task lists is empty in `onLoadFinished` in `EditTaskFragment` (https://github.com/dmfs/opentasks/blob/a764d2d35f41b705984fa208782165d35403f951/opentasks/src/main/java/org/dmfs/tasks/EditTaskFragment.java#L479),
and if it is, show a dialog message with something like:
"Please select at least one Task list in "Displayed Lists" to be able to add new tasks"
with an OK button that finishes `EditTaskActivity`.

(I've checked that the `Cursor` is empty there in this scenario)

**Comment by lemonboston** [comment]
@dmfs I've just found this note from you regarding this bug:
> In time, we will support read only task lists, so there will be the case that no writable task lists are available. Now, just show a toast or snackbar if that is the case.

So I will implement it with a SnackBar or Toast and finishing the Activity as mentioned above.
(Simpler than dialog which would need to be styled, I suppose.)
Ideally we would check for this before opening the editor but I assume this is an edge case anyway so I suppose it's okay to flash it up and remove once loader completed.

**Comment by dmfs** [comment]
Yes, this is an edge case. No need to put in too much effort for now. We can improve this later on.
