### ISSUE TITLE
Not able to create synchronized lists in app

### ISSUE THREAD

**Issue by ti-guru** [dmfs/opentasks#953]
Please add support for creation of synchronized lists on device. Installed davx5 and opentasks on Android 8.1.0: App only allows you to create a local list in displayed lists view. [This](https://github.com/dmfs/opentasks/issues/608#issuecomment-359278553) is not a solution.

**Comment by DJCrashdummy** [comment]
simply use DAVx5 to create a new list aka. calendar (the 3dot-menu). :wink: 

- - -

and the "solution" that you have to install OpenTasks before DAVx5 (as you linked it) is a fact, because android has only a calender provider and no task provider itself. - if you don't like this behaviour, it must be solved at android.

**Comment by ti-guru** [comment]
Thanks for the feedback! Still, creating lists in davx5 isn't an elegant solution. How about rolling your own as tasks.org? 

> simply use DAVx5 to create a new list aka. calendar (the 3dot-menu). 
> 
> and the "solution" that you have to install OpenTasks before DAVx5 (as you linked it) is a fact, because android has only a calender provider and no task provider itself. - if you don't like this behaviour, it must be solved at android.

**Comment by DJCrashdummy** [comment]
well IMHO this is the far more elegant solution... to create a task provider and use a system-wide sync solution. - i never understood why tasks.org uses his own sync adaper (it seems just more work, for the dev & the user). :thinking: 

- - -

anyhow i'm not 100% sure if you are kind of mixing 2 topics and it may still be possible to some day add an in-app function for creating new calendars, or at least use/"link" the DAVx5 activity to create a new calendar.
but i'm pretty sure for the foreseeable future you have to settle with the mentioned workaround.

**Comment by ti-guru** [comment]
Okey! Closing the issue.
