### ISSUE TITLE
Intent to add new task

### ISSUE THREAD

**Issue by yvolk** [dmfs/opentasks#955]
["ToDo Agenda" widget](https://github.com/andstatus/todoagenda#readme)  can show tasks from the OpenTasks app. Click on an event, shown in the widget, opens the app's "View task" screen.

Now I'm extending the "ToDo Agenda" widget with an "Add new Task" button on the widget header (in addition to existing "Add new Calendar event" button), see https://github.com/andstatus/todoagenda/issues/9

Looking into the Source code of this OpenTasks app I cannot find suitable Intent that would open "Create" Activity just like on the below screenshot.

What intent should I use?
If such intent doesn't exist yet, could you add it, please.

![Screenshot_1596903466](https://user-images.githubusercontent.com/207716/89715076-dedecd80-d9ab-11ea-9be4-a981748b03f0.png)

**Comment by dmfs** [comment]
@yvolk please see [AndroidManifest line 64](https://github.com/dmfs/opentasks/blob/master/opentasks/src/main/AndroidManifest.xml#L64) for the activity which handles this (the insert intent filter is on [line 107](https://github.com/dmfs/opentasks/blob/master/opentasks/src/main/AndroidManifest.xml#L107) 
We listen for the standard `INSERT` intent. When you call it with the OpenTasks authority (`content://org.dmfs.tasks`) the intent should launch the task editor.

**Comment by yvolk** [comment]
@dmfs Thank you Marten, it works https://github.com/andstatus/todoagenda/commit/ecc53f76a674a993080ae4f3bccf35854d83759b
