### ISSUE TITLE
F-Droid description: also mention EteSync

### ISSUE THREAD

**Issue by tasn** [dmfs/opentasks#960]
Hey, I'm the lead dev of EteSync. I would love to add EteSync to the list of supported apps on the F-Droid (and Google Play?) description if fine by you.
Here's the ticket on f-droid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7666

Thanks!

**Comment by tasn** [comment]
Just following up on this. @dmfs, would that be OK?

**Comment by tasn** [comment]
Hey @dmfs, just following up.

**Comment by dmfs** [comment]
Sorry, I missed that. Fine by me. I just gave it a :+1: .

**Comment by tasn** [comment]
Great, thanks!
