### ISSUE TITLE
Data loss caused by checklist feature (and other side effects)

### ISSUE THREAD

**Issue by sp-icy** [dmfs/opentasks#975]
Hi,

I would like to contribute something I encountered when I synchronized tasks between Thunderbird/Lightning and OpenTasks via Radicale and DAVx5.

This probably concerns OpenTasks only.

## What I tried, and why

I have been using the calendar to store notes in the description field of calendar fields, regardless if it was a real event or something to do.
Now I wanted to change my workflow, using tasks for to-dos instead.
To use tasks on both desktop and smartphone, I was going to convert some calendar events to tasks within Thunderbird/Lightning, and then sync them to my phone.

## What I found out

A)
- When a line starts with **squared brackets** `[]` (**without something inside**) this line and all following **lines get lost**. I didn't expect this data loss. A fix would be very appreciated. Details below.

B)
- All **normal lines below the first checklist item line** (that starts with `[ ]` or `[x]`) are **converted to unchecked checklist items** (`[ ]`).
  - I was surprised by this because I didn't know about OpenTasks checklist feature. I used these type of ASCII Art checklists before not just at the end but also in the middle of a calendar description text. I think the checklist feature is really nice and now that I know that there should be just one checklist at the end of the task description text, I can care about that by moving the text lines out of (here: above) the checklist area and removing the brackets that where added by OpenTasks.
  - Most important: There is **no data loss**. Just added squared brackets.
  - Therefore I see this as a personal experience. ;-) No reason to change OpenTasks. Thanks for the checklist feature.

C)
- A task that was created within Thunderbird/Lightning (with title and description text set only) gets a **status change** when saved **by OpenTasks**. Even if you don't save anything intentionally but OpenTasks saves its - let's say - special checklist changes. Details below.
  - In Thunderbird/Lightning the status is unset/empty by default. OpenTasks changes this to "needs action".
  - OpenTasks doesn't seem to know an unset status and therefore sets its default status. This seemed to be by intention, according to #807.
  - I would suggest OpenTasks to keep the status unchanged even if it is unset. In #807 it's considered as a possible behaviour for a future release, as far as I understood correctly. I'm sorry, I guess I should talk about this in #807, which is still open, don't I? Nevertheless I mentioned it here because it's part of what I found out as a whole.

I searched within the Issues section and found some tickets that could be related to the above points:
- To A and B:
  - [Crashes when attempting to display a task with a given content #286](https://github.com/dmfs/opentasks/issues/286)
  - [Rework task description/checklist. #950](https://github.com/dmfs/opentasks/pull/950)
  - [Support markdown lists with dash for checklists #875](https://github.com/dmfs/opentasks/issues/875)
- To C (and maybe A and B):
  - [Sync task status & percent complete with checklist #66](https://github.com/dmfs/opentasks/issues/66)
- To C:
  - [No STATUS #807](https://github.com/dmfs/opentasks/issues/807)

You can find my detailed test setup, process and results below.

## What I used

- OpenTasks 1.2.4 (Android app from F-Droid)
- DAVx5 3.3.6-ose (Android app from F-Droid)
- Radicale 1.1.6-1 (Ubuntu 18.04)
- Thunderbird 68.10.0, Lightning 68.9.0 (Ubuntu 18.04)

## What I did

At first I had a description text like this...
```
[]- Line 1
[] - Line 2
[ ]- Line 3
```
... and found out that after (or during) synchronizing unfortunately the data from lines 1 and 2 vanished.
Back in Thunderbird/Lightning the description text looked like this (first line empty):
```

[ ] - Line 3
```

Then I got curious and tried some more combinations. :D

### Checkbox test # 0
```
Line 1
Line 2
Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.

### Checkbox test # 1.1
```
Line 1
Line 2
[]-Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Lines 3 to 5 vanished.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Changed, same as in OpenTasks. Additionally status changed from unset/empty to "needs action".
- **Result: Data lost. Status set/changed.**

### Checkbox test # 1.2
```
Line 1
Line 2
[]- Line 3
Line 4
Line 5
```
- After sync to OpenTasks: See # 1.1
- With no intentionally saved changes in OpenTasks, after sync to Lightning: See # 1.1
- **Result: Data lost. Status set/changed.**

### Checkbox test # 1.3
```
Line 1
Line 2
[] - Line 3
Line 4
Line 5
```
- After sync to OpenTasks: See # 1.1
- With no intentionally saved changes in OpenTasks, after sync to Lightning: See # 1.1
- **Result: Data lost. Status set/changed.**

### Checkbox test # 1.4
```
Line 1
Line 2
[] -Line 3
Line 4
Line 5
```
- After sync to OpenTasks: See # 1.1
- With no intentionally saved changes in OpenTasks, after sync to Lightning: See # 1.1
- **Result: Data lost. Status set/changed.**

### Checkbox test # 1.5
```
Line 1
Line 2
[] Line 3
Line 4
Line 5
```
- After sync to OpenTasks: See # 1.1
- With no intentionally saved changes in OpenTasks, after sync to Lightning: See # 1.1
- **Result: Data lost. Status set/changed.**

### Checkbox test # 1.6
```
Line 1
Line 2
[]Line 3
Line 4
Line 5
```
- After sync to OpenTasks: See # 1.1
- With no intentionally saved changes in OpenTasks, after sync to Lightning: See # 1.1
- **Result: Data lost. Status set/changed.**

### Checkbox test # 2.1
```
Line 1
Line 2
 []-Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 2.2
```
Line 1
Line 2
 []- Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 2.3
```
Line 1
Line 2
 [] - Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 2.4
```
Line 1
Line 2
 [] -Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 2.5
```
Line 1
Line 2
 [] Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 2.6
```
Line 1
Line 2
 []Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 3.1
```
Line 1
Line 2
[ ]-Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Lines 3 to 5 became checklist items. The first item is `-Line 3`.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Changed, line 3 shown as text `[ ] -Line 3`. Additionally status changed from unset/empty to "needs action".
- Result: No data lost. But **status set/changed.**

### Checkbox test # 3.2
```
Line 1
Line 2
[ ]- Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Lines 3 to 5 became checklist items. The first item is `- Line 3`.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Changed, line 3 shown as text `[ ] - Line 3`. Additionally status changed from unset/empty to "needs action".
- Result: No data lost. But **status set/changed.**

### Checkbox test # 3.3
```
Line 1
Line 2
[ ] - Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Lines 3 to 5 became checklist items. The first item is `- Line 3`.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: See # 3.2
- Result: No data lost. But **status set/changed.**

### Checkbox test # 3.4
```
Line 1
Line 2
[ ] -Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Lines 3 to 5 became checklist items. The first item is `-Line 3`.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: See # 3.1
- Result: No data lost. But **status set/changed.**

### Checkbox test # 3.5
```
Line 1
Line 2
[ ] Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Lines 3 to 5 became checklist items. The first item is `Line 3`.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Changed, line 3 shown as text `[ ] Line 3`. Additionally status changed from unset/empty to "needs action".
- Result: No data lost. But **status set/changed.**

### Checkbox test # 3.6
```
Line 1
Line 2
[ ]Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Lines 3 to 5 became checklist items. The first item is `Line 3`.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: See # 3.5
- Result: No data lost. But **status set/changed.**

### Checkbox test # 4.1
```
Line 1
Line 2
 [ ]-Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 4.2
```
Line 1
Line 2
 [ ]- Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 4.3
```
Line 1
Line 2
 [ ] - Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 4.4
```
Line 1
Line 2
 [ ] -Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 4.5
```
Line 1
Line 2
 [ ] Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 4.6
```
Line 1
Line 2
 [ ]Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 5.1
```
Line 1
Line 2
[x]-Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Lines 3 to 5 became checklist items. The first item is `-Line 3` and checked.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Changed, line 3 shown as text `[x] -Line 3`. Additionally status changed from unset/empty to "needs action".
- Result: No data lost. But **status set/changed.**

### Checkbox test # 5.2
```
Line 1
Line 2
[x]- Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Lines 3 to 5 became checklist items. The first item is `- Line 3` and checked.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Changed, line 3 shown as text `[x] - Line 3`. Additionally status changed from unset/empty to "needs action".
- Result: No data lost. But **status set/changed.**

### Checkbox test # 5.3
```
Line 1
Line 2
[x] - Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Lines 3 to 5 became checklist items. The first item is `- Line 3` and checked.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: See # 5.2
- Result: No data lost. But **status set/changed.**

### Checkbox test # 5.4
```
Line 1
Line 2
[x] -Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Lines 3 to 5 became checklist items. The first item is `-Line 3` and checked.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: See # 5.1
- Result: No data lost. But **status set/changed.**

### Checkbox test # 5.5
```
Line 1
Line 2
[x] Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Lines 3 to 5 became checklist items. The first item is `Line 3` and checked.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Changed, line 3 shown as text `[x] Line 3`. Additionally status changed from unset/empty to "needs action".
- Result: No data lost. But **status set/changed.**

### Checkbox test # 5.6
```
Line 1
Line 2
[x]Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Lines 3 to 5 became checklist items. The first item is `Line 3` and checked.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: See # 5.5
- Result: No data lost. But **status set/changed.**

### Checkbox test # 6.1
```
Line 1
Line 2
[ok]-Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 6.2
```
Line 1
Line 2
[ok]- Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 6.3
```
Line 1
Line 2
[ok] - Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 6.4
```
Line 1
Line 2
[ok] -Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 6.5
```
Line 1
Line 2
[ok] Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

### Checkbox test # 6.6
```
Line 1
Line 2
[ok]Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation.
- Result: No changes, as expected. Good.

End of test cases :)

You already read my conclusions and questions at the top.
Thank you for your patience and stamina. ;-)
This is my very first contribution. I hope it helps.

**Comment by dmfs** [comment]
Thanks for the detailed report. I appreciate the work you've put into this. The upcoming release contains a couple of changes to improve the check list feature. In particular cases 1.x should be fixed.
I don't really consider cases when a `needs-action` `status` was added a bug. `needs-action` is the default `status` if none is given, hence the semantics are the same.
Anyway, I'm planning to refactor the task details view and I'll keep this in mind.

**Comment by dmfs** [comment]
Please let me know if this is still an issue with the current version 1.3.1.

**Comment by sp-icy** [comment]
Thank you. I'll be able to check it out when it's available on F-Droid. At the moment there's just version 1.3.0.

**Comment by sp-icy** [comment]
Hi,

I'm sorry for the delay. In the meantime there was a new version 1.4.1 which I tested today. TLDR section can be found at the bottom. ;-)

## My test setup slightly changed

- OpenTasks 1.4.1 (Android app from F-Droid)
- DAVx5 3.3.9-ose (Android app from F-Droid)
- Radicale 1.1.6-1 (Ubuntu 18.04)
- Thunderbird 78.8.1, Lightning is integrated since Thunderbird 78 (Ubuntu 18.04)

## Testing with version 1.4.1

In the first place I recreated my test tasks (with their original contents, see initial post or below) within Thunderbird.
Then I rerun the steps from my initial post. Those steps and the new results are as follows.

### Checkbox test # 0
```
Line 1
Line 2
Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Same result** as in my initial post.


### Checkbox test # 1.1
```
Line 1
Line 2
[]-Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 1.2
```
Line 1
Line 2
[]- Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 1.3
```
Line 1
Line 2
[] - Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 1.4
```
Line 1
Line 2
[] -Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 1.5
```
Line 1
Line 2
[] Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 1.6
```
Line 1
Line 2
[]Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.


### Checkbox test # 2.1
```
Line 1
Line 2
 []-Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 2.2
```
Line 1
Line 2
 []- Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 2.3
```
Line 1
Line 2
 [] - Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 2.4
```
Line 1
Line 2
 [] -Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 2.5
```
Line 1
Line 2
 [] Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 2.6
```
Line 1
Line 2
 []Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.


### Checkbox test # 3.1
```
Line 1
Line 2
[ ]-Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Line 3 became checklist item. The item is `-Line 3`. The other lines above and below are simple text areas. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 3.2
```
Line 1
Line 2
[ ]- Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Line 3 became checklist item. The item is `- Line 3`. The other lines above and below are simple text areas. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 3.3
```
Line 1
Line 2
[ ] - Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Line 3 became checklist item. The item is `- Line 3`. The other lines above and below are simple text areas. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 3.4
```
Line 1
Line 2
[ ] -Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Line 3 became checklist item. The item is `-Line 3`. The other lines above and below are simple text areas. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 3.5
```
Line 1
Line 2
[ ] Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Line 3 became checklist item. The item is `Line 3`. The other lines above and below are simple text areas. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 3.6
```
Line 1
Line 2
[ ]Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Line 3 became checklist item. The item is `Line 3`. The other lines above and below are simple text areas. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.


### Checkbox test # 4.1
```
Line 1
Line 2
 [ ]-Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Same result** as in my initial post.
- Result: No changes, as expected. Good.

### Checkbox test # 4.2
```
Line 1
Line 2
 [ ]- Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Same result** as in my initial post.
- Result: No changes, as expected. Good.

### Checkbox test # 4.3
```
Line 1
Line 2
 [ ] - Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Same result** as in my initial post.
- Result: No changes, as expected. Good.

### Checkbox test # 4.4
```
Line 1
Line 2
 [ ] -Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Same result** as in my initial post.
- Result: No changes, as expected. Good.

### Checkbox test # 4.5
```
Line 1
Line 2
 [ ] Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Same result** as in my initial post.
- Result: No changes, as expected. Good.

### Checkbox test # 4.6
```
Line 1
Line 2
 [ ]Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Same result** as in my initial post.
- Result: No changes, as expected. Good.


### Checkbox test # 5.1
```
Line 1
Line 2
[x]-Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Line 3 became checklist item. The item is `-Line 3` and checked. The other lines above and below are simple text areas. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 5.2
```
Line 1
Line 2
[x]- Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Line 3 became checklist item. The item is `- Line 3` and checked. The other lines above and below are simple text areas. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.


### Checkbox test # 5.3
```
Line 1
Line 2
[x] - Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Line 3 became checklist item. The item is `- Line 3` and checked. The other lines above and below are simple text areas. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 5.4
```
Line 1
Line 2
[x] -Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Line 3 became checklist item. The item is `-Line 3` and checked. The other lines above and below are simple text areas. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 5.5
```
Line 1
Line 2
[x] Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Line 3 became checklist item. The item is `Line 3` and checked. The other lines above and below are simple text areas. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.

### Checkbox test # 5.6
```
Line 1
Line 2
[x]Line 3
Line 4
Line 5
```
- After sync to OpenTasks: Line 3 became checklist item. The item is `Line 3` and checked. The other lines above and below are simple text areas. // **Different result**, OK now.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Different result**, OK now.
- Result: No changes, as expected. Good.


### Checkbox test # 6.1
```
Line 1
Line 2
[ok]-Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Same result** as in my initial post.
- Result: No changes, as expected. Good.

### Checkbox test # 6.2
```
Line 1
Line 2
[ok]- Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Same result** as in my initial post.
- Result: No changes, as expected. Good.

### Checkbox test # 6.3
```
Line 1
Line 2
[ok] - Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Same result** as in my initial post.
- Result: No changes, as expected. Good.

### Checkbox test # 6.4
```
Line 1
Line 2
[ok] -Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Same result** as in my initial post.
- Result: No changes, as expected. Good.

### Checkbox test # 6.5
```
Line 1
Line 2
[ok] Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Same result** as in my initial post.
- Result: No changes, as expected. Good.

### Checkbox test # 6.6
```
Line 1
Line 2
[ok]Line 3
Line 4
Line 5
```
- After sync to OpenTasks: No changes. // **Same result** as in my initial post.
- With no intentionally saved changes in OpenTasks, after sync to Lightning: Looks unchanged since task creation. // **Same result** as in my initial post.
- Result: No changes, as expected. Good.


End of test cases - round 2 ;)


## Test result summary; TLDR

- No more data loss.
- No more unexpected status changing from unset/empty to "needs action".
- If a line starts with `[ ]` or `[x]`, no matter what's following, it is interpreted as a checklist item.
- If a line starts with `[]` (without a space character inside the brackets), it is **not** interpreted as a checklist item. That's fine for me. But I wouldn't mind if this was interpreted as a valid unchecked item. I don't know what Markdown (flavour) specifications say. Just my two cents.


Thank you for your good work to maintain this app. I appreciate it.

**Comment by dmfs** [comment]
Thanks for the update. Good to hear that. Can we close this then?

**Comment by sp-icy** [comment]
Yes, we can.
Was I supposed to close this? Or can this be closed by the maintainer only? I don't see any "Close" buttons.
Sorry for not knowing. It's my first contribution like this.

**Comment by sp-icy** [comment]
I'm sorry. I guess I didn't see the "Close with comment" button because I wasn't logged in.
I do close this now. :-)

**Comment by sp-icy** [comment]
Short addition:

Above I said that the **status** didn't change any more. I was sure about that when I wrote it yesterday. Maybe I was wrong back then.
Otherwise it could have had something to do with today's additional syncing (without touching the tasks).

Whatever... Today I saw that the tasks **# 3.1** to **# 3.6** and **# 5.1** to **# 5.6** got a status change from unset/empty to "needs action". The same behaviour as decribed in my initial post.

I just wanted to add this.

As far as I understood the status changing behaviour was not subject to change now, furthermore it is not subject to discuss within this ticket.

**Comment by sp-icy** [comment]
Unfortunately I think I didn't make Thunderbird get the tasks from Radicale correctly yesterday. Sorry for the confusion. Here's my next update. Should be complete now.

The following lines changed. Only lines that were interpreted as checklist item were involved. All other lines stayed unaltered.

### Checkbox test # 3.1
Original: `[ ]-Line 3`
After: `- [ ] -Line 3`

### Checkbox test # 3.2
Original: `[ ]- Line 3`
After: `- [ ] - Line 3`

### Checkbox test # 3.3
Original: `[ ] - Line 3`
After: `- [ ] - Line 3`

### Checkbox test # 3.4
Original: `[ ] -Line 3`
After: `- [ ] -Line 3`

### Checkbox test # 3.5
Original: `[ ] Line 3`
After: `- [ ] Line 3`

### Checkbox test # 3.6
Original: `[ ]Line 3`
After: `- [ ] Line 3`

In the exact same way **# 5.1** to **# 5.6** were changed. The only difference is that those were and still are checked ("x" between brackets).

After sync to Thunderbird/Lightning...
- ... `- ` (dash and space) was added **in front of** the brackets whenever the line started directly with the brackets.
- ... ` ` (space) was added **behind** the brackets whenever there was **no space** between the brackets and the following text.

From my point of view this alteration is okay. No data is lost. `- [ ] Sample item` seems to fit Markdown specification, at least one of the flavours around.

I guess these alterations were done by intention because of #875. Therefore the ticket stays closed.

**Comment by dmfs** [comment]
Yes, these ware intentional changes to provide more interoperability.
