### ISSUE TITLE
No new version 1.3.0 on F-droid

### ISSUE THREAD

**Issue by Valdnet** [dmfs/opentasks#990]
The new version 1.3.0 was released on February 11, 2021. Until today it has not appeared on the F-droid. The current version is 1.2.4 (78500). Did something go wrong with the update?

**Comment by de-es** [comment]
The F-droid build server was down for some time. I guess there is a huge pile of apps which want to be build atm.

**Comment by schirinowski** [comment]
F-droid installed 1.3.0 for me today.

**Comment by de-es** [comment]
It was finally build this afternoon. :grin:

**Comment by Valdnet** [comment]
But it's not on the F-Droid yet :grin:.

**Comment by schirinowski** [comment]
Pardon me, it was Play Store which installed it on my device...

**Comment by Valdnet** [comment]
@dmfs Still no new version on F-Droid. Is it impossible to share an APK on Githab? Some developers do. This would speed up the download of the new version and its testing.
