### ISSUE TITLE
Multiline Checklist Items

### ISSUE THREAD

**Issue by schirinowski** [dmfs/opentasks#991]
When viewing or editing a task, it used to be possible to have mutliline checklist items. That is, if the description of an item is too long to render in one line on the screen, the line breaks to show the entire description on the screen.

In v1.3.0 the items are output in a single row, making long descriptions illegible.

![Screenshot_20210218-161445_OpenTasks](https://user-images.githubusercontent.com/47022976/108377682-90d13f00-7204-11eb-8ce1-071a61bd707d.jpg)

**Comment by dmfs** [comment]
Right, that's a ToDo left over from the rework.

**Comment by dmfs** [comment]
impllemented by #992

**Comment by schirinowski** [comment]
Thanks, Marten. I just installed 1.3.1, everything renders as it should - as expected. 👍
