### ISSUE TITLE
Cannot open settings

### ISSUE THREAD

**Issue by rEnr3n** [dmfs/opentasks#996]
OpenTasks v1.3.1
Android 10

When I press `Settings` I get android's notification setting for the app. I don't see the app's settings anywhere.

**Comment by dmfs** [comment]
That's actually the only settings we have right now but it's going to change soon. Android essentially made the old app settings obsolete (before that we only had a few notification settings too).

**Comment by dmfs** [comment]
#994 will bring the settings screen back.

**Comment by rEnr3n** [comment]
Oh ok. I thought it would have at least a setting for theme.

**Comment by dmfs** [comment]
> Oh ok. I thought it would have at least a setting for theme.

No not yet. Hopefully soon though.
